// Generated by @typespex/mcp. Do not edit.
import application from "../../mcp-application.js";
import { createPetAssistantMcpServer } from "./mcp-server.js";
import { runTypespexNodeServer } from "@typespex/mcp-runtime/node";

await runTypespexNodeServer(() => createPetAssistantMcpServer(application), application.http);
