// Generated by @typespex/mcp-emitter. Do not edit.
import { createSchemaDocument, type McpToolDefinition } from "@typespex/mcp-server";
import type { Pet, NotFoundError } from "./models.js";

export type GetPetInput = { id: string };
export type GetPetSuccess = Pet;
export type GetPetOutput = GetPetSuccess;
export type GetPetError = NotFoundError;

export type ListPetsInput = Record<string, never>;
export type ListPetsSuccess = ReadonlyArray<Pet>;
export type ListPetsOutput = ListPetsSuccess;
export type ListPetsError = never;

const schemaDocument = createSchemaDocument({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  schemas: {
    GetPetInput: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
      additionalProperties: false,
    },
    GetPetSuccess: { $ref: "#/$defs/Pet" },
    GetPetError: { $ref: "#/$defs/NotFoundError" },
    ListPetsInput: { type: "object", properties: {}, additionalProperties: false },
    ListPetsSuccess: { type: "array", items: { $ref: "#/$defs/Pet" } },
  },
  $defs: {
    Pet: {
      type: "object",
      properties: { id: { type: "string" }, name: { type: "string", minLength: 1 } },
      required: ["id", "name"],
      additionalProperties: false,
    },
    NotFoundError: {
      type: "object",
      properties: { code: { type: "string", const: "NOT_FOUND" }, message: { type: "string" } },
      required: ["code", "message"],
      additionalProperties: false,
    },
  },
});

export const mcpTools = [
  {
    name: "getPet",
    title: "Get pet",
    description: "Return a pet by its stable identifier.",
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: schemaDocument.get<GetPetInput>("GetPetInput"),
    success: schemaDocument.get<GetPetSuccess>("GetPetSuccess"),
    errors: schemaDocument.get<GetPetError>("GetPetError"),
  },
  {
    name: "listPets",
    title: "List pets",
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: schemaDocument.get<ListPetsInput>("ListPetsInput"),
    success: schemaDocument.get<ListPetsSuccess>("ListPetsSuccess"),
  },
] as const satisfies readonly McpToolDefinition[];
