// Generated by @typespex/mcp. Do not edit.
import type { Pet, NotFoundError } from "./models.js";
import {
  createGeneratedMcpServer,
  defineMcpApplication,
  type HybridMcpApplication,
  type McpTaggedToolHandler,
  type McpToolHandler,
} from "@typespex/mcp-runtime";
import { mcpTools } from "./mcp-operations.js";

export type GetPetInput = { id: string };
export type GetPetOutput = Pet;
export type GetPetError = NotFoundError;

export type ListPetsInput = Record<string, never>;
export type ListPetsOutput = ReadonlyArray<Pet>;
export type ListPetsError = never;

export interface PetAssistantMcpHandlers {
  readonly getPet: McpToolHandler<GetPetInput, GetPetOutput, GetPetError>;
  readonly listPets: McpToolHandler<ListPetsInput, ListPetsOutput, ListPetsError>;
}

export type PetAssistantMcpApplication = HybridMcpApplication<PetAssistantMcpHandlers>;

export const definePetAssistantMcpApplication = (
  application: PetAssistantMcpApplication,
): PetAssistantMcpApplication => defineMcpApplication(application);

export function createPetAssistantMcpServer(application: PetAssistantMcpApplication) {
  return createGeneratedMcpServer(
    {
      implementation: { name: "PetAssistant", version: "1.0.0" },
      instructions: "Look up pets in the TypeSpex example store",
    },
    mcpTools,
    application,
  );
}
