// Generated by @typespex/mcp-emitter. Do not edit.
import { serveMcpStdio } from "@typespex/mcp-transport-stdio";
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";

const application: PetAssistantMcpApplication = applicationDefinition;

export const petAssistantMcpStdioServer = serveMcpStdio(
  () => createPetAssistantMcpServer(application),
  application.stdio,
);
