// Generated by @typespex/mcp. Do not edit.
import application from "../../mcp-application.js";
import { createPetAssistantMcpServer } from "./mcp-server.js";
import { serveTypespexStdio } from "@typespex/mcp-runtime/stdio";

serveTypespexStdio(() => createPetAssistantMcpServer(application), application.stdio);
