// Generated by @typespex/mcp-emitter. Do not edit.
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";

const application: PetAssistantMcpApplication = applicationDefinition;
import { toHonoApp } from "@typespex/adapter-hono";
import { createTypespexHttpHandler } from "@typespex/mcp-transport-http";

const mcpHandler = createTypespexHttpHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
export const petAssistantMcpHonoApp = toHonoApp({
  handle: mcpHandler.fetch,
});
let closePromise: Promise<void> | undefined;
export const closePetAssistantMcpHonoApp = () => (closePromise ??= mcpHandler.close());
