// Generated by @typespex/mcp. Do not edit.
import application from "../../mcp-application.js";
import { createPetAssistantMcpServer } from "./mcp-server.js";
import { createTypespexHonoHandler } from "@typespex/mcp-runtime/hono";

export const petAssistantMcpHonoHandler = createTypespexHonoHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
