// Generated by @typespex/mcp. Do not edit.
import application from "../../mcp-application.js";
import { createPetAssistantMcpServer } from "./mcp-server.js";
import { createTypespexNodeHandler } from "@typespex/mcp-runtime/node";

export const petAssistantMcpExpressHandler = createTypespexNodeHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
