// Generated by @typespex/mcp-emitter. Do not edit.
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";
import { toHonoApp } from "@typespex/adapter-hono";
import { createMcpHttpHandler } from "@typespex/mcp-transport-http";

const application: PetAssistantMcpApplication = applicationDefinition;

const mcpHandler = createMcpHttpHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
export const petAssistantMcpHonoApp = toHonoApp({
  handle: mcpHandler.fetch,
});
let closePromise: Promise<void> | undefined;
export const closePetAssistantMcpHonoApp = () => (closePromise ??= mcpHandler.close());
