// Generated by @typespex/mcp. Do not edit.
import type { HttpBridgeOperation } from "@typespex/mcp-runtime/http-bridge";

export const mcpHttpBridgeOperations = {
  getPet: {
    id: "getPet",
    method: "GET",
    path: "/pets/{id}",
    parameters: [
      {
        source: ["id"],
        name: "id",
        location: "path",
        required: true,
        style: "simple",
        explode: false,
        allowReserved: false,
        value: { kind: "string" },
      },
    ],
    responses: [
      {
        statuses: [200],
        mediaTypes: ["application/json"],
        kind: "json",
        bodyValue: {
          kind: "object",
          properties: {
            id: { sourceName: "id", value: { kind: "string" }, optional: false },
            name: { sourceName: "name", value: { kind: "string" }, optional: false },
          },
        },
      },
      {
        statuses: ["default"],
        mediaTypes: ["application/json"],
        kind: "json",
        bodyValue: {
          kind: "object",
          properties: {
            code: {
              sourceName: "code",
              value: { kind: "literal", value: "NOT_FOUND" },
              optional: false,
            },
            message: { sourceName: "message", value: { kind: "string" }, optional: false },
          },
        },
        error: true,
      },
    ],
    servers: [{ url: "https://pets.example.test", fullyDefaulted: true }],
  },
  listPets: {
    id: "listPets",
    method: "GET",
    path: "/pets",
    parameters: [],
    responses: [
      {
        statuses: [200],
        mediaTypes: ["application/json"],
        kind: "json",
        bodyValue: {
          kind: "array",
          item: {
            kind: "object",
            properties: {
              id: { sourceName: "id", value: { kind: "string" }, optional: false },
              name: { sourceName: "name", value: { kind: "string" }, optional: false },
            },
          },
        },
      },
    ],
    servers: [{ url: "https://pets.example.test", fullyDefaulted: true }],
  },
} as const satisfies Readonly<Record<string, HttpBridgeOperation>>;
