// Generated by @typespex/mcp-emitter. Do not edit.
import {
  createMcpServer,
  type McpHandlersFor,
  type NativeMcpApplication,
} from "@typespex/mcp-server";
import {
  createMcpHttpBridgeApplication,
  type McpHttpBridgeApplication,
} from "@typespex/mcp-http-bridge";
import { mcpHttpBridgeOperations } from "./mcp-http-client.js";
import type { McpHttpServerOptions } from "@typespex/mcp-transport-http";
import type { McpStdioOptions } from "@typespex/mcp-transport-stdio";
import { mcpTools } from "./mcp-operations.js";
export type {
  GetPetInput,
  GetPetSuccess,
  GetPetOutput,
  GetPetError,
  ListPetsInput,
  ListPetsSuccess,
  ListPetsOutput,
  ListPetsError,
} from "./mcp-operations.js";

export type PetAssistantMcpHandlers = McpHandlersFor<typeof mcpTools>;

export type PetAssistantMcpApplication = (
  | NativeMcpApplication<PetAssistantMcpHandlers>
  | McpHttpBridgeApplication
) & { readonly http?: McpHttpServerOptions; readonly stdio?: McpStdioOptions };

export function definePetAssistantMcpApplication<
  const Application extends PetAssistantMcpApplication,
>(application: Application): Application {
  return application;
}

export function createPetAssistantMcpServer(application: PetAssistantMcpApplication) {
  const serverApplication =
    application.kind === "http-bridge"
      ? createMcpHttpBridgeApplication(mcpHttpBridgeOperations, application)
      : application;
  return createMcpServer(
    {
      implementation: { name: "PetAssistant", version: "1.0.0" },
      instructions: "Look up pets in the TypeSpex example store",
    },
    mcpTools,
    serverApplication,
  );
}
