// Generated by @typespex/mcp-emitter. Do not edit.
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";

const application: PetAssistantMcpApplication = applicationDefinition;
import { toBunHandler } from "@typespex/adapter-bun";
import { createMcpHttpHandler, resolveMcpHttpServerOptions } from "@typespex/mcp-transport-http";

const options = resolveMcpHttpServerOptions(application.http);
const mcpHandler = createMcpHttpHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
const bunHandler = toBunHandler({ handle: mcpHandler.fetch });
export const petAssistantMcpBunServer = Bun.serve({
  hostname: options.host,
  port: options.port,
  fetch: bunHandler.fetch,
  error(error) {
    options.onError?.(error);
    return new Response("Internal server error.", { status: 500 });
  },
});
let closePromise: Promise<void> | undefined;
export function closePetAssistantMcpBunServer(): Promise<void> {
  return (closePromise ??= (async () => {
    try {
      await petAssistantMcpBunServer.stop(true);
    } finally {
      await mcpHandler.close();
    }
  })());
}
