// Generated by @typespex/mcp-emitter. Do not edit.
import { createTypeSpecSchema, type GeneratedMcpTool } from "@typespex/mcp-server";
import type { Pet, NotFoundError } from "./models.js";

export type GetPetInput = { id: string };
export type GetPetSuccess = Pet;
export type GetPetOutput = GetPetSuccess;
export type GetPetError = NotFoundError;

export type ListPetsInput = Record<string, never>;
export type ListPetsSuccess = ReadonlyArray<Pet>;
export type ListPetsOutput = ListPetsSuccess;
export type ListPetsError = never;

const petSchemaDefinition = {
  type: "object",
  properties: { id: { type: "string" }, name: { type: "string", minLength: 1 } },
  required: ["id", "name"],
  additionalProperties: false,
} as const;
const notFoundErrorSchemaDefinition = {
  type: "object",
  properties: { code: { type: "string", const: "NOT_FOUND" }, message: { type: "string" } },
  required: ["code", "message"],
  additionalProperties: false,
} as const;

const getPetInput = createTypeSpecSchema<GetPetInput>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    properties: { id: { type: "string" } },
    required: ["id"],
    additionalProperties: false,
  },
});
const getPetSuccess = createTypeSpecSchema<GetPetSuccess>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $ref: "#/$defs/Pet",
    $defs: { Pet: petSchemaDefinition },
  },
});
const getPetErrors = createTypeSpecSchema<GetPetError>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $ref: "#/$defs/NotFoundError",
    $defs: { NotFoundError: notFoundErrorSchemaDefinition },
  },
});
const listPetsInput = createTypeSpecSchema<ListPetsInput>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    properties: {},
    additionalProperties: false,
  },
});
const listPetsSuccess = createTypeSpecSchema<ListPetsSuccess>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "array",
    items: { $ref: "#/$defs/Pet" },
    $defs: { Pet: petSchemaDefinition },
  },
});

export const mcpTools = [
  {
    name: "getPet",
    handler: "getPet",
    title: "Get pet",
    description: "Return a pet by its stable identifier.",

    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: getPetInput,
    success: getPetSuccess,
    errors: getPetErrors,
  },
  {
    name: "listPets",
    handler: "listPets",
    title: "List pets",

    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: listPetsInput,
    success: listPetsSuccess,
  },
] as const satisfies readonly GeneratedMcpTool[];
