// Generated by @typespex/mcp. Do not edit.
import { createTypeSpecSchema, type GeneratedMcpTool } from "@typespex/mcp-runtime";
import type { Pet, PetWire, NotFoundError, NotFoundErrorWire } from "./models.js";
import { mcpHttpBridgeOperations } from "./mcp-http-client.js";

export type GetPetInputWire = { id: string };
export type GetPetInput = { id: string };
export type GetPetSuccessWire = PetWire;
export type GetPetSuccess = Pet;
export type GetPetOutput = GetPetSuccess;
export type GetPetErrorWire = NotFoundErrorWire;
export type GetPetError = NotFoundError;

export type ListPetsInputWire = Record<string, never>;
export type ListPetsInput = Record<string, never>;
export type ListPetsSuccessWire = ReadonlyArray<PetWire>;
export type ListPetsSuccess = ReadonlyArray<Pet>;
export type ListPetsOutput = ListPetsSuccess;
export type ListPetsErrorWire = never;
export type ListPetsError = never;

const petSchemaDefinition = {
  type: "object",
  properties: { id: { type: "string" }, name: { type: "string", minLength: 1 } },
  required: ["id", "name"],
  additionalProperties: false,
} as const;
const notFoundErrorSchemaDefinition = {
  type: "object",
  properties: { code: { type: "string", const: "NOT_FOUND" }, message: { type: "string" } },
  required: ["code", "message"],
  additionalProperties: false,
} as const;

const getPetInput = createTypeSpecSchema<GetPetInputWire, GetPetInput>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    properties: { id: { type: "string" } },
    required: ["id"],
    additionalProperties: false,
  },
});
const getPetSuccess = createTypeSpecSchema<GetPetSuccessWire, GetPetSuccess>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $ref: "#/$defs/Pet",
    $defs: { Pet: petSchemaDefinition },
  },
});
const getPetErrors = createTypeSpecSchema<GetPetErrorWire, GetPetError>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $ref: "#/$defs/NotFoundError",
    $defs: { NotFoundError: notFoundErrorSchemaDefinition },
  },
});
const listPetsInput = createTypeSpecSchema<ListPetsInputWire, ListPetsInput>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    properties: {},
    additionalProperties: false,
  },
});
const listPetsSuccess = createTypeSpecSchema<ListPetsSuccessWire, ListPetsSuccess>({
  schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "array",
    items: { $ref: "#/$defs/Pet" },
    $defs: { Pet: petSchemaDefinition },
  },
});

export const mcpTools = [
  {
    name: "getPet",
    handler: "getPet",
    title: "Get pet",
    description: "Return a pet by its stable identifier.",

    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: getPetInput,
    success: getPetSuccess,
    errors: getPetErrors,

    http: mcpHttpBridgeOperations["getPet"],
  },
  {
    name: "listPets",
    handler: "listPets",
    title: "List pets",

    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
    input: listPetsInput,
    success: listPetsSuccess,

    http: mcpHttpBridgeOperations["listPets"],
  },
] as const satisfies readonly GeneratedMcpTool[];
