// Generated by @typespex/mcp-emitter. Do not edit.
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";

const application: PetAssistantMcpApplication = applicationDefinition;
import { createServer } from "node:http";
import { toNodeHandler } from "@typespex/adapter-node";
import { createMcpHttpHandler, resolveMcpHttpServerOptions } from "@typespex/mcp-transport-http";

const options = resolveMcpHttpServerOptions(application.http);
const mcpHandler = createMcpHttpHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
const nodeHandler = toNodeHandler({ handle: mcpHandler.fetch });
let closeMcpHandlerPromise: Promise<void> | undefined;
const closeMcpHandler = () => (closeMcpHandlerPromise ??= mcpHandler.close());
export const petAssistantMcpNodeServer = createServer(
  (request, response) => void nodeHandler(request, response),
);
petAssistantMcpNodeServer.on("close", () => void closeMcpHandler());
try {
  await new Promise<void>((resolve, reject) => {
    const onError = (error: Error) => {
      petAssistantMcpNodeServer.off("listening", onListening);
      reject(error);
    };
    const onListening = () => {
      petAssistantMcpNodeServer.off("error", onError);
      resolve();
    };
    petAssistantMcpNodeServer.once("error", onError);
    petAssistantMcpNodeServer.once("listening", onListening);
    petAssistantMcpNodeServer.listen(options.port, options.host);
  });
} catch (error) {
  await closeMcpHandler();
  throw error;
}

export async function closePetAssistantMcpNodeServer(): Promise<void> {
  if (petAssistantMcpNodeServer.listening) {
    await new Promise<void>((resolve, reject) => {
      petAssistantMcpNodeServer.close((error) => (error ? reject(error) : resolve()));
    });
  }
  await closeMcpHandler();
}
