// Generated by @typespex/mcp. Do not edit.
import application from "../../mcp-application.js";
import { createPetAssistantMcpServer } from "./mcp-server.js";
import { runTypespexBunServer } from "@typespex/mcp-runtime/bun";

runTypespexBunServer(() => createPetAssistantMcpServer(application), application.http);
