// Generated by @typespex/mcp-emitter. Do not edit.
import applicationDefinition from "../../mcp-application.js";
import { createPetAssistantMcpServer, type PetAssistantMcpApplication } from "./mcp-server.js";
import { toExpressHandler, type ExpressRequestHandler } from "@typespex/adapter-express";
import { createMcpHttpHandler } from "@typespex/mcp-transport-http";

const application: PetAssistantMcpApplication = applicationDefinition;

const mcpHandler = createMcpHttpHandler(
  () => createPetAssistantMcpServer(application),
  application.http,
);
export const petAssistantMcpExpressHandler: ExpressRequestHandler = toExpressHandler({
  handle: mcpHandler.fetch,
});
let closePromise: Promise<void> | undefined;
export const closePetAssistantMcpExpressHandler = () => (closePromise ??= mcpHandler.close());
