// Generated by @typespex/mcp. Do not edit.
export interface Pet {
  id: string;
  name: string;
}

export type PetWire = Pet;

export interface NotFoundError {
  code: "NOT_FOUND";
  message: string;
}

export type NotFoundErrorWire = NotFoundError;
