import type { Model, Enum, Union, Type } from "@typespec/compiler";
import { isArrayModelType, isRecordModelType } from "@typespec/compiler";
import { isMetadata } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { typeToTs } from "./type-reference.js";

/**
 * Emit TypeScript interfaces for all models used by the service.
 */
export function emitModels(ctx: EmitterCtx): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");

  // Collect all named types from the service namespace
  collectModelsFromNamespace(ctx, ctx.service.namespace, lines);

  return lines.join("\n");
}

function collectModelsFromNamespace(
  ctx: EmitterCtx,
  ns: Type & { models?: Map<string, Model>; enums?: Map<string, Enum>; unions?: Map<string, Union>; namespaces?: Map<string, any> },
  lines: string[],
): void {
  if (ns.models) {
    for (const [, model] of ns.models) {
      emitModel(ctx, model, lines);
    }
  }

  if (ns.enums) {
    for (const [, enumType] of ns.enums) {
      emitEnum(ctx, enumType, lines);
    }
  }

  if (ns.unions) {
    for (const [, union] of ns.unions) {
      emitUnion(ctx, union, lines);
    }
  }

  // Recurse into child namespaces
  if (ns.namespaces) {
    for (const [, childNs] of ns.namespaces) {
      collectModelsFromNamespace(ctx, childNs, lines);
    }
  }
}

function emitModel(ctx: EmitterCtx, model: Model, lines: string[]): void {
  if (!model.name || model.name === "") return;

  // Skip built-in TypeSpec models
  if (model.namespace?.name === "TypeSpec") return;

  // Skip array and record model types — they don't need their own interface
  if (
    isArrayModelType(ctx.program, model) ||
    isRecordModelType(ctx.program, model)
  )
    return;

  if (ctx.emittedModels.has(model.name)) return;
  ctx.emittedModels.add(model.name);

  const props = [...model.properties.values()];
  const baseModel = model.baseModel && shouldEmitBaseModel(ctx, model.baseModel)
    ? model.baseModel
    : undefined;
  const extendsClause = baseModel ? ` extends ${baseModel.name}` : "";
  lines.push(`export interface ${model.name}${extendsClause} {`);
  for (const prop of props) {
    if (isMetadata(ctx.program, prop)) continue;
    const optional = prop.optional ? "?" : "";
    const tsType = typeToTs(ctx, prop.type);
    lines.push(`  ${prop.name}${optional}: ${tsType};`);
  }
  lines.push("}");
  lines.push("");
}

function shouldEmitBaseModel(ctx: EmitterCtx, model: Model): boolean {
  return Boolean(
    model.name &&
      model.name !== "" &&
      model.namespace?.name !== "TypeSpec" &&
      !isArrayModelType(ctx.program, model) &&
      !isRecordModelType(ctx.program, model),
  );
}

function emitEnum(ctx: EmitterCtx, enumType: Enum, lines: string[]): void {
  if (!enumType.name) return;
  if (ctx.emittedModels.has(enumType.name)) return;
  ctx.emittedModels.add(enumType.name);

  const members = [...enumType.members.values()];
  const memberTypes = members
    .map((m) =>
      typeof m.value === "string"
        ? JSON.stringify(m.value)
        : m.value != null
          ? String(m.value)
          : JSON.stringify(m.name),
    )
    .join(" | ");

  lines.push(`export type ${enumType.name} = ${memberTypes};`);
  lines.push("");
}

function emitUnion(ctx: EmitterCtx, union: Union, lines: string[]): void {
  if (!union.name) return;
  if (ctx.emittedModels.has(union.name)) return;
  ctx.emittedModels.add(union.name);

  const variants = [...union.variants.values()];
  const variantTypes = variants.map((v) => typeToTs(ctx, v.type)).join(" | ");

  lines.push(`export type ${union.name} = ${variantTypes};`);
  lines.push("");
}
