import type { HttpOperation } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { buildServerEmission } from "./server-emission.js";

export function emitServerRouter(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");
  lines.push(
    'import type { HttpInterpreterOptions, HttpRouter, MatchedRequestContext } from "@typespex/runtime/server";',
  );
  lines.push('import { bindRoute, createHttpRouter } from "@typespex/runtime/server";');
  lines.push(`import type { ${ctx.serviceName}Server } from "./server.js";`);

  const operationConsts = emission.groups.map((group) => `${group.exportName}Operations`);
  lines.push(`import { ${operationConsts.join(", ")} } from "./server-operations.js";`);
  lines.push("");

  lines.push(
    `export function create${ctx.serviceName}ServerRouter<Ctx extends MatchedRequestContext>(implementation: ${ctx.serviceName}Server<Ctx>, options?: HttpInterpreterOptions<Ctx>): HttpRouter {`,
  );
  lines.push("  return createHttpRouter([");

  for (const group of emission.groups) {
    const groupAccess = group.interfaceName
      ? `implementation.${group.propertyName}`
      : "implementation";

    const operationsConst = `${group.exportName}Operations`;
    for (const operation of group.operations) {
      lines.push(
        `    bindRoute(${operationsConst}.${operation.name}, ${groupAccess}.${operation.name}),`,
      );
    }
  }

  lines.push("  ], options);");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
