import type { Model, Enum, Union, Type } from "@typespec/compiler";
import { isArrayModelType, isRecordModelType } from "@typespec/compiler";
import { isMetadata } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { templateParametersToTs, typeToTs } from "./type-reference.js";
import { tsIdentifier, tsPropertyDeclaration } from "./typescript-names.js";

/**
 * Emit TypeScript interfaces for all models used by the service.
 */
export function emitModels(ctx: EmitterCtx): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");

  // Collect all named types from the service namespace
  collectModelsFromNamespace(ctx, ctx.service.namespace, lines);

  return lines.join("\n");
}

function collectModelsFromNamespace(
  ctx: EmitterCtx,
  ns: Type & { models?: Map<string, Model>; enums?: Map<string, Enum>; unions?: Map<string, Union>; namespaces?: Map<string, any> },
  lines: string[],
): void {
  if (ns.models) {
    for (const [, model] of ns.models) {
      emitModel(ctx, model, lines);
    }
  }

  if (ns.enums) {
    for (const [, enumType] of ns.enums) {
      emitEnum(ctx, enumType, lines);
    }
  }

  if (ns.unions) {
    for (const [, union] of ns.unions) {
      emitUnion(ctx, union, lines);
    }
  }

  // Recurse into child namespaces
  if (ns.namespaces) {
    for (const [, childNs] of ns.namespaces) {
      collectModelsFromNamespace(ctx, childNs, lines);
    }
  }
}

function emitModel(ctx: EmitterCtx, model: Model, lines: string[]): void {
  if (!model.name || model.name === "") return;

  // Skip built-in TypeSpec models
  if (model.namespace?.name === "TypeSpec") return;

  // Skip array and record model types — they don't need their own interface
  if (
    isArrayModelType(ctx.program, model) ||
    isRecordModelType(ctx.program, model)
  )
    return;

  if (ctx.emittedModels.has(model.name)) return;
  ctx.emittedModels.add(model.name);

  const props = [...model.properties.values()];
  const baseModel = getBaseModelReference(ctx, model);
  const modelName = tsIdentifier(model.name, "Model");
  const typeParams = templateParametersToTs(ctx, model);
  const extendsClause = baseModel ? ` extends ${baseModel}` : "";
  lines.push(`export interface ${modelName}${typeParams}${extendsClause} {`);
  for (const prop of props) {
    if (isMetadata(ctx.program, prop)) continue;
    const tsType = typeToTs(ctx, prop.type);
    lines.push(`  ${tsPropertyDeclaration(prop.name, tsType, { optional: prop.optional })};`);
  }
  lines.push("}");
  lines.push("");
}

function getBaseModelReference(ctx: EmitterCtx, model: Model): string | undefined {
  const node = model.node;
  const resolvedBase = node && "extends" in node && node.extends
    ? ctx.program.checker.getTypeForNode(node.extends)
    : undefined;
  const baseModel = resolvedBase?.kind === "Model" ? resolvedBase : model.baseModel;
  if (!baseModel || !shouldEmitBaseModel(ctx, baseModel)) return undefined;
  const sourceReference = node && "extends" in node && node.extends
    ? typeReferenceExpressionToTs(ctx, node.extends)
    : undefined;
  return sourceReference ?? typeToTs(ctx, baseModel);
}

function typeReferenceExpressionToTs(ctx: EmitterCtx, expression: unknown): string | undefined {
  if (!isObject(expression) || !("target" in expression) || !("arguments" in expression)) {
    return undefined;
  }

  const target = referenceTargetToTs(expression.target);
  if (!target) return undefined;

  const args = Array.isArray(expression.arguments)
    ? expression.arguments
      .map((arg) => isObject(arg) && "argument" in arg
        ? expressionTypeToTs(ctx, arg.argument)
        : "unknown")
    : [];

  return args.length > 0 ? `${target}<${args.join(", ")}>` : target;
}

function referenceTargetToTs(target: unknown): string | undefined {
  if (!isObject(target)) return undefined;
  if ("sv" in target && typeof target.sv === "string") {
    return tsIdentifier(target.sv, "Model");
  }
  if ("base" in target && "id" in target) {
    const base = referenceTargetToTs(target.base);
    const id = isObject(target.id) && "sv" in target.id && typeof target.id.sv === "string"
      ? tsIdentifier(target.id.sv, "Model")
      : undefined;
    return base && id ? `${base}.${id}` : undefined;
  }
  return undefined;
}

function expressionTypeToTs(ctx: EmitterCtx, expression: unknown): string {
  if (!isObject(expression)) return "unknown";
  return typeToTs(ctx, ctx.program.checker.getTypeForNode(expression as never));
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function shouldEmitBaseModel(ctx: EmitterCtx, model: Model): boolean {
  return Boolean(
    model.name &&
      model.name !== "" &&
      model.namespace?.name !== "TypeSpec" &&
      !isArrayModelType(ctx.program, model) &&
      !isRecordModelType(ctx.program, model),
  );
}

function emitEnum(ctx: EmitterCtx, enumType: Enum, lines: string[]): void {
  if (!enumType.name) return;
  if (ctx.emittedModels.has(enumType.name)) return;
  ctx.emittedModels.add(enumType.name);

  const members = [...enumType.members.values()];
  const memberTypes = members
    .map((m) =>
      typeof m.value === "string"
        ? JSON.stringify(m.value)
        : m.value != null
          ? String(m.value)
          : JSON.stringify(m.name),
    )
    .join(" | ");

  lines.push(`export type ${tsIdentifier(enumType.name, "Enum")} = ${memberTypes};`);
  lines.push("");
}

function emitUnion(ctx: EmitterCtx, union: Union, lines: string[]): void {
  if (!union.name) return;
  if (ctx.emittedModels.has(union.name)) return;
  ctx.emittedModels.add(union.name);

  const variants = [...union.variants.values()];
  const variantTypes = variants.map((v) => typeToTs(ctx, v.type)).join(" | ");

  lines.push(`export type ${tsIdentifier(union.name, "Union")} = ${variantTypes};`);
  lines.push("");
}
