import {
  getDoc,
  getSummary,
  getTags,
  type DecoratorApplication,
  type Namespace,
  type Type,
} from "@typespec/compiler";
import type { HttpOperation } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { getNamespaceFullName } from "./namespace-names.js";
import { tsIdentifier, tsObjectKey } from "./typescript-names.js";

interface HintDefinition {
  readonly id: string;
  readonly exportName: string;
  readonly typeText: string;
}

export interface EmittedHintEntry {
  readonly keyExportName: string;
  readonly valueExpression: string;
}

const BUILTIN_HINTS: readonly HintDefinition[] = [
  { id: "TypeSpec.doc", exportName: "typeSpecDocHint", typeText: "string" },
  { id: "TypeSpec.summary", exportName: "typeSpecSummaryHint", typeText: "string" },
  { id: "TypeSpec.tags", exportName: "typeSpecTagsHint", typeText: "readonly string[]" },
] as const;

export function emitServerHints(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): string {
  const definitions = collectHintDefinitions(ctx, httpOperations);

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");
  lines.push('import { createHintKey } from "@typespex/runtime/server";');
  lines.push("");

  for (const definition of definitions) {
    const exportName = tsIdentifier(definition.exportName, "hint");
    lines.push(
      `export const ${exportName} = createHintKey<${definition.typeText}>(${JSON.stringify(definition.id)});`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

export function emitHintEntries(
  ctx: EmitterCtx,
  target: Type,
): EmittedHintEntry[] {
  const entries: EmittedHintEntry[] = [];
  const doc = getDoc(ctx.program, target);
  if (doc !== undefined) {
    entries.push({
      keyExportName: "typeSpecDocHint",
      valueExpression: JSON.stringify(doc),
    });
  }

  const summary = getSummary(ctx.program, target);
  if (summary !== undefined) {
    entries.push({
      keyExportName: "typeSpecSummaryHint",
      valueExpression: JSON.stringify(summary),
    });
  }

  const tags = getTags(ctx.program, target);
  if (tags.length > 0) {
    entries.push({
      keyExportName: "typeSpecTagsHint",
      valueExpression: JSON.stringify(tags),
    });
  }

  if ("decorators" in target) {
    for (const decorator of target.decorators) {
      const entry = emitCustomDecoratorHintEntry(decorator);
      if (entry) {
        entries.push(entry);
      }
    }
  }

  return dedupeHintEntries(entries);
}

function collectHintDefinitions(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): HintDefinition[] {
  const definitions = new Map<string, HintDefinition>();
  for (const builtin of BUILTIN_HINTS) {
    definitions.set(builtin.id, builtin);
  }

  const addFromTarget = (target: Type) => {
    if (!("decorators" in target)) return;
    for (const decorator of target.decorators) {
      const custom = customHintDefinition(decorator);
      if (!custom) continue;
      const existing = definitions.get(custom.id);
      if (!existing) {
        definitions.set(custom.id, custom);
      } else if (existing.typeText !== custom.typeText) {
        definitions.set(custom.id, { ...existing, typeText: `${existing.typeText} | ${custom.typeText}` });
      }
    }
  };

  addFromTarget(ctx.service.namespace);
  for (const op of httpOperations) {
    for (const namespace of getOperationNamespaces(ctx.service.namespace, op.operation.namespace)) {
      addFromTarget(namespace);
    }
    addFromTarget(op.operation);
  }

  return [...definitions.values()].sort((a, b) => a.id.localeCompare(b.id));
}

export function getOperationNamespaces(
  serviceNamespace: Namespace,
  namespace: Namespace | undefined,
): Namespace[] {
  const namespaces: Namespace[] = [];
  let current = namespace;

  while (current && current.name !== "") {
    if (current !== serviceNamespace) {
      namespaces.push(current);
    }
    current = current.namespace;
  }

  namespaces.reverse();
  return namespaces;
}

function emitCustomDecoratorHintEntry(
  decorator: DecoratorApplication,
): EmittedHintEntry | undefined {
  const resolved = resolveCustomHint(decorator);
  if (!resolved) return undefined;

  return {
    keyExportName: resolved.definition.exportName,
    valueExpression: valueToTs(resolved.value),
  };
}

function customHintDefinition(
  decorator: DecoratorApplication,
): HintDefinition | undefined {
  return resolveCustomHint(decorator)?.definition;
}

/** Resolves a decorator into a hint definition + marshalled value. Single marshal. */
function resolveCustomHint(
  decorator: DecoratorApplication,
): { definition: HintDefinition; value: JsonLike } | undefined {
  const id = getDecoratorId(decorator);
  if (!id || isBuiltinDecorator(id)) return undefined;

  const value = marshalDecoratorArguments(decorator);
  if (value === undefined) return undefined;

  return {
    definition: {
      id,
      exportName: hintExportName(id),
      typeText: valueTypeToTs(value),
    },
    value,
  };
}

function getDecoratorId(decorator: DecoratorApplication): string | undefined {
  const definition = decorator.definition;
  if (!definition) return undefined;

  const namespace = getNamespaceFullName(definition.namespace);
  const name = definition.name.replace(/^@/, "");
  return namespace ? `${namespace}.${name}` : name;
}

function isBuiltinDecorator(id: string): boolean {
  return id.startsWith("TypeSpec.");
}

function marshalDecoratorArguments(
  decorator: DecoratorApplication,
): JsonLike | undefined {
  const args = decorator.args
    .map((arg) => marshalJsValue(arg.jsValue))
    .filter((x): x is JsonLike => x !== undefined);

  if (args.length !== decorator.args.length) {
    return undefined;
  }

  if (args.length === 0) return true;
  if (args.length === 1) return args[0];
  return args;
}

type JsonLike =
  | string
  | number
  | boolean
  | null
  | readonly JsonLike[]
  | { readonly [key: string]: JsonLike };

function marshalJsValue(value: unknown): JsonLike | undefined {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }

  if (Array.isArray(value)) {
    const marshalled = value.map(marshalJsValue);
    return marshalled.every((x) => x !== undefined) ? marshalled as JsonLike[] : undefined;
  }

  if (typeof value === "object") {
    if (value === null) return null;
    if ("kind" in value || "entityKind" in value || "valueKind" in value) {
      return undefined;
    }

    const out: Record<string, JsonLike> = {};
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
      const marshalled = marshalJsValue(item);
      if (marshalled === undefined) return undefined;
      out[key] = marshalled;
    }
    return out;
  }

  return undefined;
}

function valueToTs(value: JsonLike): string {
  if (value === null) return "null";
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(valueToTs).join(", ")}]`;
  }
  return `{ ${Object.entries(value)
    .map(([key, item]) => `${tsObjectKey(key)}: ${valueToTs(item)}`)
    .join(", ")} }`;
}

function valueTypeToTs(value: JsonLike): string {
  if (value === null) return "null";
  switch (typeof value) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "readonly unknown[]";
    return `readonly [${value.map(valueTypeToTs).join(", ")}]`;
  }

  const fields = Object.entries(value).map(
    ([key, item]) => `readonly ${JSON.stringify(key)}: ${valueTypeToTs(item)}`,
  );
  return `{ ${fields.join("; ")} }`;
}

function hintExportName(id: string): string {
  const parts = id.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "customHint";

  const [first, ...rest] = parts;
  const camel = [
    first.charAt(0).toLowerCase() + first.slice(1),
    ...rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)),
  ].join("");
  return tsIdentifier(`${camel}Hint`, "customHint");
}

function dedupeHintEntries(entries: EmittedHintEntry[]): EmittedHintEntry[] {
  const map = new Map<string, EmittedHintEntry>();
  for (const entry of entries) {
    map.set(entry.keyExportName, entry);
  }
  return [...map.values()];
}
