import type { EmitterCtx } from "./ctx.js";
import type { HttpOperation } from "@typespec/http";
import {
  emitResultResponseEncoder,
} from "./emit-server-common.js";
import {
  type InputDecoderEntry,
  type DecoderEmission,
  emitDecoder,
  getServerInputDecoderImports,
} from "./server-input-decoders.js";
import { buildServerEmission } from "./server-emission.js";

export function emitServerOperations(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];

  // --- Header ---
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");

  // --- Imports (multi-line) ---
  lines.push('import type { Decoder, ServerOperation } from "@typespex/runtime/server";');
  lines.push("import {");
  lines.push("  Either,");
  lines.push("  createHints,");
  lines.push("  emptyHints,");
  lines.push("  ResponseEncoders,");
  for (const name of getServerInputDecoderImports()) {
    lines.push(`  ${name},`);
  }
  lines.push('} from "@typespex/runtime/server";');
  lines.push(`import * as ServerHints from "./${ctx.fileNames.serverHints}.js";`);
  if (emission.modelImports.length > 0) {
    lines.push(`import type { ${emission.modelImports.join(", ")} } from "./${ctx.fileNames.models}.js";`);
  }
  lines.push("");

  // --- Input decoders + Operations per group ---
  for (const group of emission.groups) {
    const inputsName = `${group.exportName}Input`;
    const outputsName = `${group.exportName}Output`;
    const decodersByOpId = new Map<string, DecoderEmission>();
    const allEntries: InputDecoderEntry[] = [];

    const allHoisted: string[] = [];
    for (const operation of group.operations) {
      const decoder = emitDecoder(ctx, operation.httpOperation, inputsName, operation.name);
      allEntries.push(...decoder.inputEntries);
      allHoisted.push(...decoder.hoistedDecoders);
      decodersByOpId.set(operation.operationId, decoder);
    }

    // Emit hoisted lazy decoders for recursive models
    for (const line of allHoisted) {
      lines.push(line);
    }
    if (allHoisted.length > 0) lines.push("");

    // Emit grouped input decoders object
    if (allEntries.length > 0) {
      lines.push(`const ${inputsName} = {`);
      for (const entry of allEntries) {
        for (const line of entry.lines) {
          lines.push(line);
        }
      }
      lines.push("};");
      lines.push("");
    }

    // Emit grouped output encoders object
    lines.push(`const ${outputsName} = {`);
    for (const operation of group.operations) {
      lines.push(`  ${operation.name}: ${emitResultResponseEncoder(ctx, operation.httpOperation, operation.resultType)},`);
    }
    lines.push("};");
    lines.push("");

    // Emit operations
    lines.push(`export const ${group.exportName}Operations = {`);

    for (const operation of group.operations) {
      const decoder = decodersByOpId.get(operation.operationId)!;

      lines.push(`  ${operation.name}: {`);
      emitEndpoint(lines, emission.serviceName, operation);

      // decodeInput — expression-body arrow, async only when body is involved
      const asyncPrefix = decoder.isAsync ? "async " : "";
      if (decoder.needsPathParams) {
        lines.push(`    decodeInput: ${asyncPrefix}(request, pathParams) =>`);
      } else if (decoder.isAsync) {
        lines.push(`    decodeInput: ${asyncPrefix}(request) =>`);
      } else {
        lines.push(`    decodeInput: () =>`);
      }
      lines.push(`      ${decoder.decodeExpression},`);

      emitResultEncoderLine(lines, operation, outputsName);

      lines.push(
        `  } satisfies ServerOperation<${operation.inputType}, ${operation.resultType}>,`,
      );
      lines.push("");
    }

    lines.push("} as const;");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Endpoint emission — compact
// ---------------------------------------------------------------------------

function emitEndpoint(
  lines: string[],
  serviceName: string,
  operation: {
    serviceHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    namespaces: ReadonlyArray<{
      name: string;
      fullName: string;
      hints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    }>;
    name: string;
    operationId: string;
    method: string;
    path: string;
    operationHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
  },
): void {
  lines.push("    endpoint: {");
  lines.push(`      service: { name: ${JSON.stringify(serviceName)}, hints: ${emitHintsExpression(operation.serviceHints)} },`);

  if (operation.namespaces.length === 0) {
    lines.push("      namespaces: [],");
  } else {
    lines.push("      namespaces: [");
    for (const ns of operation.namespaces) {
      lines.push(`        { name: ${JSON.stringify(ns.name)}, fullName: ${JSON.stringify(ns.fullName)}, hints: ${emitHintsExpression(ns.hints)} },`);
    }
    lines.push("      ],");
  }

  lines.push("      operation: {");
  lines.push(`        name: ${JSON.stringify(operation.name)},`);
  lines.push(`        operationId: ${JSON.stringify(operation.operationId)},`);
  lines.push(`        method: ${JSON.stringify(operation.method)} as const,`);
  lines.push(`        path: ${JSON.stringify(operation.path)},`);
  lines.push(`        hints: ${emitHintsExpression(operation.operationHints)},`);
  lines.push("      },");
  lines.push("    },");
}

// ---------------------------------------------------------------------------
// Encode emission — uses structured results, no regex parsing
// ---------------------------------------------------------------------------

function emitResultEncoderLine(
  lines: string[],
  operation: { name: string; resultType: string; httpOperation: HttpOperation },
  outputsName: string,
): void {
  if (operation.resultType === "void") {
    lines.push(`    encodeResult: () => ${outputsName}.${operation.name}.encode(undefined),`);
  } else {
    lines.push(`    encodeResult: (result: ${operation.resultType}) => ${outputsName}.${operation.name}.encode(result),`);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitHintsExpression(
  entries: ReadonlyArray<{ keyExportName: string; valueExpression: string }>,
): string {
  if (entries.length === 0) return "emptyHints()";
  const items = entries
    .map((e) => `[ServerHints.${e.keyExportName}, ${e.valueExpression}]`)
    .join(", ");
  return `createHints([${items}])`;
}
