import type { HttpOperation } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { buildServerEmission, collectReferencedModelImports } from "./server-emission.js";

export function emitServer(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");
  lines.push(
    'import type { MatchedRequestContext, OperationHandler } from "@typespex/runtime/server";',
  );
  const modelImports = collectReferencedModelImports(emission);
  if (modelImports.length > 0) {
    lines.push("import type {");
    lines.push(`  ${modelImports.join(",\n  ")}`);
    lines.push(`} from "./${ctx.fileNames.models}.js";`);
    lines.push("");
  }

  for (const group of emission.groups) {
    if (!group.interfaceName) continue;

    lines.push(`export interface ${group.interfaceName}Server<Ctx = MatchedRequestContext> {`);
    for (const operation of group.operations) {
      lines.push(
        `  readonly ${operation.name}: OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>;`,
      );
    }
    lines.push("}");
    lines.push("");
  }

  lines.push(`export interface ${emission.serviceName}Server<Ctx = MatchedRequestContext> {`);
  for (const group of emission.groups) {
    if (group.interfaceName) {
      lines.push(`  readonly ${group.propertyName}: ${group.interfaceName}Server<Ctx>;`);
      continue;
    }

    for (const operation of group.operations) {
      lines.push(
        `  readonly ${operation.name}: OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>;`,
      );
    }
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
