import type { Enum, Expression, Model, Scalar, Type, Union, UnionVariant } from "@typespec/compiler";
import { isArrayModelType, isRecordModelType, isTemplateDeclaration } from "@typespec/compiler";
import { SyntaxKind, type TypeReferenceNode } from "@typespec/compiler/ast";
import { isMetadata } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { templateParametersToTs, typeToTs } from "./type-reference.js";
import { tsIdentifier, tsPropertyDeclaration } from "./typescript-names.js";

const SEMANTIC_TYPE_REFERENCE_NAMES = new Set([
  "Array", "Record", "string", "int8", "int16", "int32", "int64",
  "uint8", "uint16", "uint32", "uint64", "float32", "float64",
  "boolean", "bytes", "plainDate", "plainTime", "utcDateTime",
  "offsetDateTime", "duration", "url", "numeric", "integer", "float",
  "decimal", "decimal128", "safeint", "void", "null", "never", "unknown",
]);

/**
 * Emit TypeScript interfaces for all models used by the service.
 */
export function emitModels(ctx: EmitterCtx): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");

  // Collect all named types from the service namespace
  collectModelsFromNamespace(ctx, ctx.service.namespace, lines);

  return lines.join("\n");
}

function collectModelsFromNamespace(
  ctx: EmitterCtx,
  ns: Type & {
    models?: Map<string, Model>;
    scalars?: Map<string, Scalar>;
    enums?: Map<string, Enum>;
    unions?: Map<string, Union>;
    namespaces?: Map<string, any>;
  },
  lines: string[],
): void {
  if (ns.models) {
    for (const [, model] of ns.models) {
      emitModel(ctx, model, lines);
    }
  }

  if (ns.scalars) {
    for (const [, scalar] of ns.scalars) {
      emitScalar(ctx, scalar, lines);
    }
  }

  if (ns.enums) {
    for (const [, enumType] of ns.enums) {
      emitEnum(ctx, enumType, lines);
    }
  }

  if (ns.unions) {
    for (const [, union] of ns.unions) {
      emitUnion(ctx, union, lines);
    }
  }

  // Recurse into child namespaces
  if (ns.namespaces) {
    for (const [, childNs] of ns.namespaces) {
      collectModelsFromNamespace(ctx, childNs, lines);
    }
  }
}

function emitModel(ctx: EmitterCtx, model: Model, lines: string[]): void {
  if (!model.name || model.name === "") return;

  // Skip built-in TypeSpec models
  if (model.namespace?.name === "TypeSpec") return;

  // Skip array and record model types — they don't need their own interface
  if (
    isArrayModelType(ctx.program, model) ||
    isRecordModelType(ctx.program, model)
  )
    return;

  if (ctx.emittedModels.has(model.name)) return;
  ctx.emittedModels.add(model.name);

  const props = [...model.properties.values()];
  const baseModel = getBaseModelReference(ctx, model);
  const modelName = tsIdentifier(model.name, "Model");
  const typeParams = templateParametersToTs(ctx, model);
  const extendsClause = baseModel ? ` extends ${baseModel}` : "";
  lines.push(`export interface ${modelName}${typeParams}${extendsClause} {`);
  for (const prop of props) {
    if (isMetadata(ctx.program, prop)) continue;
    const tsType = typeToTs(ctx, prop.type);
    lines.push(`  ${tsPropertyDeclaration(prop.name, tsType, { optional: prop.optional })};`);
  }
  lines.push("}");
  lines.push("");
}

function getBaseModelReference(ctx: EmitterCtx, model: Model): string | undefined {
  const node = model.node;
  const baseExpression = node?.kind === SyntaxKind.ModelStatement
    ? node.extends
    : undefined;
  const resolvedBase = baseExpression
    ? ctx.program.checker.getTypeForNode(baseExpression)
    : undefined;
  const baseModel = resolvedBase?.kind === "Model" ? resolvedBase : model.baseModel;
  if (!baseModel || !shouldEmitBaseModel(ctx, baseModel)) return undefined;
  const sourceReference = baseExpression ? typeReferenceExpressionToTs(ctx, baseExpression) : undefined;
  return sourceReference ?? typeToTs(ctx, baseModel);
}

function typeReferenceExpressionToTs(ctx: EmitterCtx, expression: Expression): string | undefined {
  if (expression.kind !== SyntaxKind.TypeReference) return undefined;
  if (shouldUseSemanticTypeReference(expression)) return undefined;

  const target = referenceTargetToTs(expression.target);
  if (!target) return undefined;

  const args = expression.arguments.map((arg) =>
    expressionSourceToTs(ctx, arg.argument) ?? expressionTypeToTs(ctx, arg.argument)
  );
  return args.length > 0 ? `${target}<${args.join(", ")}>` : target;
}

function shouldUseSemanticTypeReference(expression: TypeReferenceNode): boolean {
  return expression.target.kind === SyntaxKind.Identifier &&
    SEMANTIC_TYPE_REFERENCE_NAMES.has(expression.target.sv);
}

function referenceTargetToTs(target: TypeReferenceNode["target"]): string | undefined {
  switch (target.kind) {
    case SyntaxKind.Identifier:
      return tsIdentifier(target.sv, "Model");
    case SyntaxKind.MemberExpression:
      // models.ts currently flattens TypeSpec namespaces to top-level exports.
      // Keep qualified source refs resolvable by emitting the leaf type name.
      return tsIdentifier(target.id.sv, "Model");
    default:
      return undefined;
  }
}

function expressionTypeToTs(ctx: EmitterCtx, expression: Expression): string {
  return typeToTs(ctx, ctx.program.checker.getTypeForNode(expression));
}

function expressionSourceToTs(ctx: EmitterCtx, expression: Expression): string | undefined {
  switch (expression.kind) {
    case SyntaxKind.TypeReference:
      return typeReferenceExpressionToTs(ctx, expression);
    case SyntaxKind.ValueOfExpression:
      return expressionSourceToTs(ctx, expression.target);
    default:
      return undefined;
  }
}

function shouldEmitBaseModel(ctx: EmitterCtx, model: Model): boolean {
  return Boolean(
    model.name &&
      model.name !== "" &&
      model.namespace?.name !== "TypeSpec" &&
      !isArrayModelType(ctx.program, model) &&
      !isRecordModelType(ctx.program, model),
  );
}

function emitEnum(ctx: EmitterCtx, enumType: Enum, lines: string[]): void {
  if (!enumType.name) return;
  if (ctx.emittedModels.has(enumType.name)) return;
  ctx.emittedModels.add(enumType.name);

  const members = [...enumType.members.values()];
  const memberTypes = members
    .map((m) =>
      typeof m.value === "string"
        ? JSON.stringify(m.value)
        : m.value != null
          ? String(m.value)
          : JSON.stringify(m.name),
    )
    .join(" | ");

  lines.push(`export type ${tsIdentifier(enumType.name, "Enum")} = ${memberTypes};`);
  lines.push("");
}

function emitScalar(ctx: EmitterCtx, scalar: Scalar, lines: string[]): void {
  if (!scalar.name || scalar.namespace?.name === "TypeSpec") return;
  if (!isTemplateDeclaration(scalar)) return;
  if (ctx.emittedModels.has(scalar.name)) return;
  ctx.emittedModels.add(scalar.name);

  const scalarName = tsIdentifier(scalar.name, "Scalar");
  const typeParams = templateParametersToTs(ctx, scalar);
  const baseType = scalar.baseScalar ? typeToTs(ctx, scalar.baseScalar) : "unknown";
  lines.push(`export type ${scalarName}${typeParams} = ${baseType};`);
  lines.push("");
}

function emitUnion(ctx: EmitterCtx, union: Union, lines: string[]): void {
  if (!union.name) return;
  if (ctx.emittedModels.has(union.name)) return;
  ctx.emittedModels.add(union.name);

  const typeParams = templateParametersToTs(ctx, union);
  const variants = [...union.variants.values()];
  const variantTypes = variants.map((v) => unionVariantToTs(ctx, v)).join(" | ");

  lines.push(`export type ${tsIdentifier(union.name, "Union")}${typeParams} = ${variantTypes};`);
  lines.push("");
}

function unionVariantToTs(ctx: EmitterCtx, variant: UnionVariant): string {
  const source = variant.node?.kind === SyntaxKind.UnionVariant
    ? expressionSourceToTs(ctx, variant.node.value)
    : undefined;
  return source ?? typeToTs(ctx, variant.type);
}
