import type { EmitterCtx } from "./ctx.js";
import type { HttpOperation } from "@typespec/http";
import {
  emitErrorEncoder,
  emitSuccessExpression,
} from "./emit-server-common.js";
import {
  type CodecEntry,
  type DecoderEmission,
  emitDecoder,
  getServerCodecImports,
} from "./server-codecs.js";
import { buildServerEmission } from "./server-emission.js";

export function emitServerOperations(
  ctx: EmitterCtx,
  httpOperations: HttpOperation[],
): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];

  // --- Header ---
  lines.push("// AUTO-GENERATED by @typespex/emitter — do not edit");
  lines.push("");

  // --- Imports (multi-line) ---
  lines.push('import type { ServerOperation } from "@typespex/runtime/server";');
  lines.push("import {");
  lines.push("  Either,");
  lines.push("  absurd,");
  lines.push("  createHints,");
  lines.push("  emptyHints,");
  for (const name of getServerCodecImports()) {
    lines.push(`  ${name},`);
  }
  lines.push('} from "@typespex/runtime/server";');
  lines.push('import * as ServerHints from "./server-hints.js";');
  if (emission.modelImports.length > 0) {
    lines.push(`import type { ${emission.modelImports.join(", ")} } from "./models.js";`);
  }
  lines.push("");

  // --- Codecs + Operations per group ---
  for (const group of emission.groups) {
    const codecsName = `${group.exportName}Codecs`;
    const decodersByOpId = new Map<string, DecoderEmission>();
    const allEntries: CodecEntry[] = [];

    for (const operation of group.operations) {
      const decoder = emitDecoder(ctx, operation.httpOperation, codecsName, operation.name);
      allEntries.push(...decoder.codecEntries);
      decodersByOpId.set(operation.operationId, decoder);
    }

    // Emit grouped codecs object
    if (allEntries.length > 0) {
      lines.push(`const ${codecsName} = {`);
      for (const entry of allEntries) {
        for (const line of entry.lines) {
          lines.push(line);
        }
      }
      lines.push("};");
      lines.push("");
    }

    // Emit operations
    lines.push(`export const ${group.exportName}Operations = {`);

    for (const operation of group.operations) {
      const decoder = decodersByOpId.get(operation.operationId)!;

      lines.push(`  ${operation.name}: {`);
      emitEndpoint(lines, emission.serviceName, operation);

      // decodeInput — expression-body arrow, async only when body is involved
      const asyncPrefix = decoder.isAsync ? "async " : "";
      if (decoder.needsPathParams) {
        lines.push(`    decodeInput: ${asyncPrefix}(request, pathParams) =>`);
      } else if (decoder.isAsync) {
        lines.push(`    decodeInput: ${asyncPrefix}(request) =>`);
      } else {
        lines.push(`    decodeInput: () =>`);
      }
      lines.push(`      ${decoder.decodeExpression},`);

      emitSuccessEncoderLine(lines, ctx, operation);
      emitErrorEncoderLines(lines, ctx, operation);

      lines.push(
        `  } satisfies ServerOperation<${operation.inputType}, ${operation.errorType}, ${operation.successType}>,`,
      );
      lines.push("");
    }

    lines.push("} as const;");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Endpoint emission — compact
// ---------------------------------------------------------------------------

function emitEndpoint(
  lines: string[],
  serviceName: string,
  operation: {
    serviceHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    namespaces: ReadonlyArray<{
      name: string;
      fullName: string;
      hints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    }>;
    name: string;
    operationId: string;
    method: string;
    path: string;
    operationHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
  },
): void {
  lines.push("    endpoint: {");
  lines.push(`      service: { name: ${JSON.stringify(serviceName)}, hints: ${emitHintsExpression(operation.serviceHints)} },`);

  if (operation.namespaces.length === 0) {
    lines.push("      namespaces: [],");
  } else {
    lines.push("      namespaces: [");
    for (const ns of operation.namespaces) {
      lines.push(`        { name: ${JSON.stringify(ns.name)}, fullName: ${JSON.stringify(ns.fullName)}, hints: ${emitHintsExpression(ns.hints)} },`);
    }
    lines.push("      ],");
  }

  lines.push("      operation: {");
  lines.push(`        name: ${JSON.stringify(operation.name)},`);
  lines.push(`        operationId: ${JSON.stringify(operation.operationId)},`);
  lines.push(`        method: ${JSON.stringify(operation.method)} as const,`);
  lines.push(`        path: ${JSON.stringify(operation.path)},`);
  lines.push(`        hints: ${emitHintsExpression(operation.operationHints)},`);
  lines.push("      },");
  lines.push("    },");
}

// ---------------------------------------------------------------------------
// Encode emission — uses structured results, no regex parsing
// ---------------------------------------------------------------------------

function emitSuccessEncoderLine(
  lines: string[],
  ctx: EmitterCtx,
  operation: { successType: string; httpOperation: HttpOperation },
): void {
  const expr = emitSuccessExpression(ctx, operation.httpOperation);
  if (operation.successType === "void") {
    lines.push(`    encodeOutput: () => ${expr},`);
  } else {
    lines.push(`    encodeOutput: (output: ${operation.successType}) => ${expr},`);
  }
}

function emitErrorEncoderLines(
  lines: string[],
  ctx: EmitterCtx,
  operation: { errorType: string; httpOperation: HttpOperation },
): void {
  const result = emitErrorEncoder(ctx, operation.httpOperation);
  if (result.kind === "expression") {
    lines.push(`    encodeError: (error: ${operation.errorType}) => ${result.expression},`);
  } else {
    lines.push(`    encodeError: (error: ${operation.errorType}) => {`);
    for (const line of result.lines) {
      lines.push(line);
    }
    lines.push("    },");
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitHintsExpression(
  entries: ReadonlyArray<{ keyExportName: string; valueExpression: string }>,
): string {
  if (entries.length === 0) return "emptyHints()";
  const items = entries
    .map((e) => `[ServerHints.${e.keyExportName}, ${e.valueExpression}]`)
    .join(", ");
  return `createHints([${items}])`;
}
