import type {
  Enum,
  Expression,
  Model,
  Scalar,
  Type,
  Union,
  UnionVariant,
} from "@typespec/compiler";
import { isArrayModelType, isTemplateDeclaration } from "@typespec/compiler";
import { SyntaxKind, type TypeReferenceNode } from "@typespec/compiler/ast";
import { getGeneratedTypeName, hasGeneratedTypeNameCollision, type EmitterCtx } from "./ctx.js";
import { addTemporalImport } from "./datetime-mode.js";
import { discriminatedUnionBodyToTs, resolveDiscriminatedUnion } from "./discriminated-unions.js";
import { isHttpFileModel, isHttpPartModel } from "./http-models.js";
import { isPureRecordModel } from "./model-indexer.js";
import { getNamespaceFullName } from "./namespace-names.js";
import {
  isTemplatedScalarReference,
  modelAdditionalPropertiesToTs,
  templateParametersToTs,
  typeToTs,
} from "./type-reference.js";
import { tsIdentifier, tsPropertyDeclaration } from "./typescript-names.js";
import { enumMemberLiteralExpression } from "./numeric-literals.js";

/**
 * Emit TypeScript interfaces for all models used by the service.
 */
export function emitModels(ctx: EmitterCtx): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");

  for (const type of ctx.namedTypes) {
    switch (type.kind) {
      case "Model":
        emitModel(ctx, type, lines);
        break;
      case "Scalar":
        emitScalar(ctx, type, lines);
        break;
      case "Enum":
        emitEnum(ctx, type, lines);
        break;
      case "Union":
        emitUnion(ctx, type, lines);
        break;
    }
  }

  addTemporalImport(lines, "type");
  return lines.join("\n");
}

function emitModel(ctx: EmitterCtx, model: Model, lines: string[]): void {
  if (!model.name || model.name === "") return;

  // Skip built-in TypeSpec models
  if (model.namespace?.name === "TypeSpec") return;

  // Collection aliases do not need their own interface. Mixed record models do:
  // their declared fields and their explicit indexer carry distinct semantics.
  if (isArrayModelType(ctx.program, model) || isPureRecordModel(model)) return;

  if (ctx.emittedModels.has(model)) return;
  ctx.emittedModels.add(model);

  const props = [...model.properties.values()];
  const baseModel = getBaseModelReference(ctx, model);
  const modelName = getGeneratedTypeName(ctx, model, "Model");
  const typeParams = templateParametersToTs(ctx, model);
  const extendsClause = baseModel ? ` extends ${baseModel}` : "";
  lines.push(`export interface ${modelName}${typeParams}${extendsClause} {`);
  for (const prop of props) {
    const tsType = typeToTs(ctx, prop.type);
    lines.push(`  ${tsPropertyDeclaration(prop.name, tsType, { optional: prop.optional })};`);
  }
  const indexer = modelAdditionalPropertiesToTs(ctx, model);
  if (indexer) lines.push(`  ${indexer};`);
  lines.push("}");
  lines.push("");
}

function getBaseModelReference(ctx: EmitterCtx, model: Model): string | undefined {
  const node = model.node;
  const baseExpression = node?.kind === SyntaxKind.ModelStatement ? node.extends : undefined;
  const resolvedBase = baseExpression
    ? ctx.program.checker.getTypeForNode(baseExpression)
    : undefined;
  const baseModel = resolvedBase?.kind === "Model" ? resolvedBase : model.baseModel;
  if (!baseModel || !shouldEmitBaseModel(ctx, baseModel)) return undefined;
  const sourceReference = baseExpression
    ? typeReferenceExpressionToTs(ctx, baseExpression)
    : undefined;
  return sourceReference ?? typeToTs(ctx, baseModel);
}

function typeReferenceExpressionToTs(ctx: EmitterCtx, expression: Expression): string | undefined {
  if (expression.kind !== SyntaxKind.TypeReference) return undefined;

  const resolved = ctx.program.checker.getTypeForNode(expression);
  if (shouldUseSemanticTypeReference(ctx, resolved)) return undefined;
  if (isHttpPartModel(ctx.program, resolved) || isHttpFileModel(ctx.program, resolved)) {
    return undefined;
  }

  const target = referenceTargetToTs(ctx, expression.target);
  if (!target) return undefined;

  const args = expression.arguments.map(
    (arg) => expressionSourceToTs(ctx, arg.argument) ?? expressionTypeToTs(ctx, arg.argument),
  );
  return args.length > 0 ? `${target}<${args.join(", ")}>` : target;
}

function shouldUseSemanticTypeReference(ctx: EmitterCtx, type: Type): boolean {
  if (type.kind === "Intrinsic") return true;
  if (type.kind === "Scalar") {
    return (
      getNamespaceFullName(type.namespace) === "TypeSpec" ||
      (!isTemplatedScalarReference(type) && !hasGeneratedTypeNameCollision(ctx, type))
    );
  }
  return type.kind === "Model" && getNamespaceFullName(type.namespace) === "TypeSpec";
}

function referenceTargetToTs(
  ctx: EmitterCtx,
  target: TypeReferenceNode["target"],
): string | undefined {
  const resolved = ctx.program.checker.getTypeForNode(target);
  if (
    resolved.kind === "Model" ||
    resolved.kind === "Scalar" ||
    resolved.kind === "Enum" ||
    resolved.kind === "Union"
  ) {
    return getGeneratedTypeName(ctx, resolved, "Model");
  }

  switch (target.kind) {
    case SyntaxKind.Identifier:
      return tsIdentifier(target.sv, "Model");
    case SyntaxKind.MemberExpression:
      // models.ts currently flattens TypeSpec namespaces to top-level exports.
      // Keep qualified source refs resolvable by emitting the leaf type name.
      return tsIdentifier(target.id.sv, "Model");
    default:
      return undefined;
  }
}

function expressionTypeToTs(ctx: EmitterCtx, expression: Expression): string {
  return typeToTs(ctx, ctx.program.checker.getTypeForNode(expression));
}

function expressionSourceToTs(ctx: EmitterCtx, expression: Expression): string | undefined {
  switch (expression.kind) {
    case SyntaxKind.TypeReference:
      return typeReferenceExpressionToTs(ctx, expression);
    case SyntaxKind.ValueOfExpression:
      return expressionSourceToTs(ctx, expression.target);
    default:
      return undefined;
  }
}

function shouldEmitBaseModel(ctx: EmitterCtx, model: Model): boolean {
  return Boolean(
    model.name &&
    model.name !== "" &&
    model.namespace?.name !== "TypeSpec" &&
    !isArrayModelType(ctx.program, model) &&
    !isPureRecordModel(model),
  );
}

function emitEnum(ctx: EmitterCtx, enumType: Enum, lines: string[]): void {
  if (!enumType.name) return;
  if (ctx.emittedModels.has(enumType)) return;
  ctx.emittedModels.add(enumType);

  const members = [...enumType.members.values()];
  const memberTypes = members
    .map((member) => enumMemberLiteralExpression(ctx.program, member))
    .join(" | ");

  lines.push(`export type ${getGeneratedTypeName(ctx, enumType, "Enum")} = ${memberTypes};`);
  lines.push("");
}

function emitScalar(ctx: EmitterCtx, scalar: Scalar, lines: string[]): void {
  if (!scalar.name || scalar.namespace?.name === "TypeSpec") return;
  if (!isTemplateDeclaration(scalar) && !hasGeneratedTypeNameCollision(ctx, scalar)) return;
  if (ctx.emittedModels.has(scalar)) return;
  ctx.emittedModels.add(scalar);

  const scalarName = getGeneratedTypeName(ctx, scalar, "Scalar");
  const typeParams = templateParametersToTs(ctx, scalar);
  const baseType = scalar.baseScalar ? typeToTs(ctx, scalar.baseScalar) : "unknown";
  lines.push(`export type ${scalarName}${typeParams} = ${baseType};`);
  lines.push("");
}

function emitUnion(ctx: EmitterCtx, union: Union, lines: string[]): void {
  if (!union.name) return;
  if (ctx.emittedModels.has(union)) return;
  ctx.emittedModels.add(union);

  const typeParams = templateParametersToTs(ctx, union);
  const discriminated = resolveDiscriminatedUnion(ctx.program, union);
  const variantTypes = discriminated
    ? discriminatedUnionBodyToTs(discriminated, ({ variant }) => unionVariantToTs(ctx, variant))
    : [...union.variants.values()].map((variant) => unionVariantToTs(ctx, variant)).join(" | ");

  lines.push(
    `export type ${getGeneratedTypeName(ctx, union, "Union")}${typeParams} = ${variantTypes};`,
  );
  lines.push("");
}

function unionVariantToTs(ctx: EmitterCtx, variant: UnionVariant): string {
  const source =
    variant.node?.kind === SyntaxKind.UnionVariant
      ? expressionSourceToTs(ctx, variant.node.value)
      : undefined;
  return source ?? typeToTs(ctx, variant.type);
}
