import type { HttpOperation } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { addTemporalImport } from "./datetime-mode.js";
import { buildServerEmission, collectReferencedModelImports } from "./server-emission.js";
import { tsIdentifier, tsPropertyDeclaration } from "./typescript-names.js";

export function emitServer(ctx: EmitterCtx, httpOperations: HttpOperation[]): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");
  lines.push(
    'import type { MatchedRequestContext, OperationHandler } from "@typespex/http-server";',
  );
  const modelImports = collectReferencedModelImports(emission);
  if (modelImports.length > 0) {
    lines.push("import type {");
    lines.push(`  ${modelImports.join(",\n  ")}`);
    lines.push(`} from "./${ctx.fileNames.models}.js";`);
    lines.push("");
  }
  if (emission.payloadTypeAliases.length > 0) {
    lines.push(...emission.payloadTypeAliases);
    lines.push("");
  }

  for (const group of emission.groups) {
    if (!group.interfaceName) continue;

    const interfaceName = group.exportName;
    lines.push(`export interface ${interfaceName}Server<Ctx = MatchedRequestContext> {`);
    for (const operation of group.operations) {
      lines.push(
        `  ${tsPropertyDeclaration(operation.propertyName, `OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>`, { readonly: true })};`,
      );
    }
    lines.push("}");
    lines.push("");
  }

  const serviceName = tsIdentifier(emission.serviceName, "Service");
  lines.push(`export interface ${serviceName}Server<Ctx = MatchedRequestContext> {`);
  for (const group of emission.groups) {
    if (group.interfaceName) {
      const interfaceName = group.exportName;
      lines.push(
        `  ${tsPropertyDeclaration(group.propertyName, `${interfaceName}Server<Ctx>`, { readonly: true })};`,
      );
      continue;
    }

    for (const operation of group.operations) {
      lines.push(
        `  ${tsPropertyDeclaration(operation.propertyName, `OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>`, { readonly: true })};`,
      );
    }
  }
  lines.push("}");
  lines.push("");

  addTemporalImport(lines, "type");
  return lines.join("\n");
}
