import type { HttpOperation } from "@typespec/http";
import type { EmitterCtx } from "./ctx.js";
import { buildServerEmission } from "./server-emission.js";
import { tsIdentifier, tsPropertyAccess } from "./typescript-names.js";

export function emitServerRouter(ctx: EmitterCtx, httpOperations: HttpOperation[]): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");
  lines.push(
    'import type { ComposableHttpRouter, HttpRouterOptions, MatchedRequestContext } from "@typespex/http-server";',
  );
  lines.push('import { bindRoute, createHttpRouter } from "@typespex/http-server";');
  const serviceName = tsIdentifier(ctx.serviceName, "Service");
  lines.push(`import type { ${serviceName}Server } from "./${ctx.fileNames.server}.js";`);

  const operationConsts = emission.groups.map((group) => `${group.exportName}Operations`);
  lines.push(
    `import { ${operationConsts.join(", ")} } from "./${ctx.fileNames.serverOperations}.js";`,
  );
  lines.push("");

  lines.push(
    `export function create${serviceName}ServerRouter<Ctx extends MatchedRequestContext>(implementation: ${serviceName}Server<Ctx>, options?: HttpRouterOptions<Ctx>): ComposableHttpRouter {`,
  );
  lines.push("  return createHttpRouter([");

  for (const group of emission.groups) {
    const groupAccess = group.interfaceName
      ? tsPropertyAccess("implementation", group.propertyName)
      : "implementation";

    const operationsConst = `${group.exportName}Operations`;
    for (const operation of group.operations) {
      lines.push(
        `    bindRoute(${tsPropertyAccess(operationsConst, operation.propertyName)}, ${tsPropertyAccess(groupAccess, operation.propertyName)}),`,
      );
    }
  }

  lines.push("  ], options);");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
