import type { EmitterCtx } from "./ctx.js";
import { addTemporalImport } from "./datetime-mode.js";
import type { HttpOperation } from "@typespec/http";
import { emitResultResponseEncoder } from "./server-response-encoder.js";
import { getJsonWireSerializerDeclarations } from "./json-wire-transforms.js";
import { getPayloadTypeAliasDeclarations } from "./payload-context.js";
import {
  type InputDecoderEntry,
  type DecoderEmission,
  emitDecoder,
  getServerInputDecoderImports,
} from "./server-input-decoders.js";
import { buildServerEmission } from "./server-emission.js";
import { tsLiteral, tsObjectKey, tsPropertyAccess } from "./typescript-names.js";
import type { RoutePattern } from "./uri-template.js";
import { getXmlCodecDeclarations } from "./xml-wire-codecs.js";

export function emitServerOperations(ctx: EmitterCtx, httpOperations: HttpOperation[]): string {
  const emission = buildServerEmission(ctx, httpOperations);
  const responseEncoders = new Map<HttpOperation, string>();
  for (const group of emission.groups) {
    for (const operation of group.operations) {
      responseEncoders.set(
        operation.httpOperation,
        emitResultResponseEncoder(ctx, operation.httpOperation, operation.resultType),
      );
    }
  }
  const inputDecoders = new Map<HttpOperation, DecoderEmission>();
  for (const group of emission.groups) {
    const inputsName = `${group.exportName}Input`;
    for (const operation of group.operations) {
      inputDecoders.set(
        operation.httpOperation,
        emitDecoder(ctx, operation.httpOperation, inputsName, operation.propertyName),
      );
    }
  }
  const xmlCodecDeclarations = getXmlCodecDeclarations(ctx);
  const jsonSerializerDeclarations = getJsonWireSerializerDeclarations(ctx);
  const payloadTypeAliases = getPayloadTypeAliasDeclarations(ctx);
  const inputDecoderText = [...inputDecoders.values()]
    .flatMap((decoder) => [
      decoder.decodeExpression,
      ...decoder.inputEntries.flatMap((entry) => entry.lines),
      ...decoder.hoistedDecoders,
    ])
    .join("\n");
  const usesJsonSerializers =
    jsonSerializerDeclarations.length > 0 ||
    xmlCodecDeclarations.some((declaration) => declaration.includes("JsonSerializers.")) ||
    inputDecoderText.includes("JsonSerializers.") ||
    [...responseEncoders.values()].some((encoder) => encoder.includes("JsonSerializers."));
  const usesXmlCodecs =
    xmlCodecDeclarations.length > 0 ||
    inputDecoderText.includes("XmlCodecs.") ||
    [...responseEncoders.values()].some((encoder) => encoder.includes("XmlCodecs."));
  const usesStringifyJson = [...responseEncoders.values()].some((encoder) =>
    encoder.includes("stringifyJson("),
  );
  const lines: string[] = [];

  // --- Header ---
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");

  // --- Imports (multi-line) ---
  const runtimeTypes = ["Decoder", "ServerOperation"];
  if (jsonSerializerDeclarations.length > 0) runtimeTypes.push("JsonSerializer");
  if (xmlCodecDeclarations.length > 0) runtimeTypes.push("XmlCodec");
  lines.push(`import type { ${runtimeTypes.join(", ")} } from "@typespex/http-server";`);
  lines.push("import {");
  lines.push("  Either,");
  lines.push("  createHints,");
  lines.push("  emptyHints,");
  lines.push("  ResponseEncoders,");
  if (usesJsonSerializers) lines.push("  JsonSerializers,");
  if (usesXmlCodecs) lines.push("  XmlCodecs,");
  if (usesStringifyJson) lines.push("  stringifyJson,");
  for (const name of getServerInputDecoderImports(ctx, httpOperations)) {
    lines.push(`  ${name},`);
  }
  lines.push('} from "@typespex/http-server";');
  lines.push(`import * as ServerHints from "./${ctx.fileNames.serverHints}.js";`);
  if (emission.modelImports.length > 0) {
    lines.push(
      `import type { ${emission.modelImports.join(", ")} } from "./${ctx.fileNames.models}.js";`,
    );
  }
  lines.push("");
  if (payloadTypeAliases.length > 0) {
    lines.push(...payloadTypeAliases);
    lines.push("");
  }
  if (jsonSerializerDeclarations.length > 0) {
    lines.push(...jsonSerializerDeclarations);
    lines.push("");
  }
  if (xmlCodecDeclarations.length > 0) {
    lines.push(...xmlCodecDeclarations);
    lines.push("");
  }

  // --- Input decoders + Operations per group ---
  const emittedHoisted = new Set<string>();
  for (const group of emission.groups) {
    const inputsName = `${group.exportName}Input`;
    const outputsName = `${group.exportName}Output`;
    const allEntries: InputDecoderEntry[] = [];

    const allHoisted = new Set<string>();
    for (const operation of group.operations) {
      const decoder = inputDecoders.get(operation.httpOperation)!;
      allEntries.push(...decoder.inputEntries);
      for (const declaration of decoder.hoistedDecoders) {
        if (!emittedHoisted.has(declaration)) allHoisted.add(declaration);
      }
    }

    // Emit hoisted lazy decoders for recursive models
    for (const line of allHoisted) {
      lines.push(line);
      emittedHoisted.add(line);
    }
    if (allHoisted.size > 0) lines.push("");

    // Emit grouped input decoders object
    if (allEntries.length > 0) {
      lines.push(`const ${inputsName} = {`);
      for (const entry of allEntries) {
        for (const line of entry.lines) {
          lines.push(line);
        }
      }
      lines.push("};");
      lines.push("");
    }

    // Emit grouped output encoders object
    lines.push(`const ${outputsName} = {`);
    for (const operation of group.operations) {
      lines.push(
        `  ${tsObjectKey(operation.propertyName)}: ${responseEncoders.get(operation.httpOperation)!},`,
      );
    }
    lines.push("};");
    lines.push("");

    // Emit operations
    lines.push(`export const ${group.exportName}Operations = {`);

    for (const operation of group.operations) {
      const decoder = inputDecoders.get(operation.httpOperation)!;

      lines.push(`  ${tsObjectKey(operation.propertyName)}: {`);
      emitEndpoint(lines, emission.serviceName, operation);

      // decodeInput — expression-body arrow, async only when body is involved
      const asyncPrefix = decoder.isAsync ? "async " : "";
      if (decoder.needsPathParams) {
        lines.push(`    decodeInput: ${asyncPrefix}(request, pathParams) =>`);
      } else if (decoder.isAsync) {
        lines.push(`    decodeInput: ${asyncPrefix}(request) =>`);
      } else {
        lines.push(`    decodeInput: () =>`);
      }
      lines.push(`      ${decoder.decodeExpression},`);

      emitResultEncoderLine(lines, operation, outputsName);

      lines.push(`  } satisfies ServerOperation<${operation.inputType}, ${operation.resultType}>,`);
      lines.push("");
    }

    lines.push("} as const;");
    lines.push("");
  }

  addTemporalImport(lines, "value");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Endpoint emission — compact
// ---------------------------------------------------------------------------

function emitEndpoint(
  lines: string[],
  serviceName: string,
  operation: {
    serviceHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    namespaces: ReadonlyArray<{
      name: string;
      fullName: string;
      hints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    }>;
    name: string;
    operationId: string;
    method: string;
    path: string;
    routePatterns: readonly RoutePattern[];
    routeSelection?: {
      readonly headers?: readonly {
        readonly name: string;
        readonly values: readonly string[];
        readonly kind: "exact" | "media-type";
      }[];
      readonly query?: readonly {
        readonly name: string;
        readonly value: string;
      }[];
    };
    operationHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
  },
): void {
  lines.push("    endpoint: {");
  lines.push(
    `      service: { name: ${tsLiteral(serviceName)}, hints: ${emitHintsExpression(operation.serviceHints)} },`,
  );

  if (operation.namespaces.length === 0) {
    lines.push("      namespaces: [],");
  } else {
    lines.push("      namespaces: [");
    for (const ns of operation.namespaces) {
      lines.push(
        `        { name: ${tsLiteral(ns.name)}, fullName: ${tsLiteral(ns.fullName)}, hints: ${emitHintsExpression(ns.hints)} },`,
      );
    }
    lines.push("      ],");
  }

  lines.push("      operation: {");
  lines.push(`        name: ${tsLiteral(operation.name)},`);
  lines.push(`        operationId: ${tsLiteral(operation.operationId)},`);
  lines.push(`        method: ${tsLiteral(operation.method)} as const,`);
  lines.push(`        path: ${tsLiteral(operation.path)},`);
  if (operation.routePatterns.length === 1) {
    lines.push(`        routePattern: ${tsLiteral(operation.routePatterns[0])},`);
  } else {
    lines.push(`        routePatterns: ${tsLiteral(operation.routePatterns)},`);
  }
  if (operation.routeSelection) {
    lines.push(`        routeSelection: ${tsLiteral(operation.routeSelection)},`);
  }
  lines.push(`        hints: ${emitHintsExpression(operation.operationHints)},`);
  lines.push("      },");
  lines.push("    },");
}

// ---------------------------------------------------------------------------
// Encode emission — uses structured results, no regex parsing
// ---------------------------------------------------------------------------

function emitResultEncoderLine(
  lines: string[],
  operation: {
    propertyName: string;
    resultType: string;
    httpOperation: HttpOperation;
  },
  outputsName: string,
): void {
  const encoderAccess = tsPropertyAccess(outputsName, operation.propertyName);
  if (operation.resultType === "void") {
    lines.push(`    encodeResult: () => ${encoderAccess}.encode(undefined),`);
  } else {
    lines.push(
      `    encodeResult: (result: ${operation.resultType}) => ${encoderAccess}.encode(result),`,
    );
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitHintsExpression(
  entries: ReadonlyArray<{ keyExportName: string; valueExpression: string }>,
): string {
  if (entries.length === 0) return "emptyHints()";
  const items = entries
    .map((e) => `[${tsPropertyAccess("ServerHints", e.keyExportName)}, ${e.valueExpression}]`)
    .join(", ");
  return `createHints([${items}])`;
}
