import { addTemporalImport } from "./datetime-mode.js";
import type { ServerPlan } from "./server-plan.js";
import { tsIdentifier, tsPropertyDeclaration } from "./typescript-names.js";

export function renderServer(plan: ServerPlan): string {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");
  lines.push(
    'import type { MatchedRequestContext, OperationHandler } from "@typespex/http-server";',
  );
  if (plan.handlerModelImports.length > 0) {
    lines.push("import type {");
    lines.push(`  ${plan.handlerModelImports.join(",\n  ")}`);
    lines.push(`} from "./${plan.fileNames.models}.js";`);
    lines.push("");
  }
  if (plan.handlerPayloadTypeAliases.length > 0) {
    lines.push(...plan.handlerPayloadTypeAliases);
    lines.push("");
  }

  for (const group of plan.groups) {
    if (!group.interfaceName) continue;

    const interfaceName = group.exportName;
    lines.push(`export interface ${interfaceName}Server<Ctx = MatchedRequestContext> {`);
    for (const operation of group.operations) {
      lines.push(
        `  ${tsPropertyDeclaration(operation.propertyName, `OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>`, { readonly: true })};`,
      );
    }
    lines.push("}");
    lines.push("");
  }

  const serviceName = tsIdentifier(plan.serviceName, "Service");
  lines.push(`export interface ${serviceName}Server<Ctx = MatchedRequestContext> {`);
  for (const group of plan.groups) {
    if (group.interfaceName) {
      const interfaceName = group.exportName;
      lines.push(
        `  ${tsPropertyDeclaration(group.propertyName, `${interfaceName}Server<Ctx>`, { readonly: true })};`,
      );
      continue;
    }

    for (const operation of group.operations) {
      lines.push(
        `  ${tsPropertyDeclaration(operation.propertyName, `OperationHandler<${operation.inputType}, ${operation.resultType}, Ctx>`, { readonly: true })};`,
      );
    }
  }
  lines.push("}");
  lines.push("");

  addTemporalImport(lines, "type");
  return lines.join("\n");
}
