import { addTemporalImport } from "./datetime-mode.js";
import { type InputDecoderEntry } from "./server-input-decoders.js";
import type { ServerPlan } from "./server-plan.js";
import { tsLiteral, tsObjectKey, tsPropertyAccess } from "./typescript-names.js";
import type { RoutePattern } from "./uri-template.js";

export function renderServerOperations(plan: ServerPlan): string {
  const inputDecoderText = plan.groups
    .flatMap((group) => group.operations.map((operation) => operation.inputDecoder))
    .flatMap((decoder) => [
      decoder.decodeExpression,
      ...decoder.inputEntries.flatMap((entry) => entry.lines),
      ...decoder.hoistedDecoders,
    ])
    .join("\n");
  const usesJsonSerializers =
    plan.jsonSerializerDeclarations.length > 0 ||
    plan.xmlCodecDeclarations.some((declaration) => declaration.includes("JsonSerializers.")) ||
    inputDecoderText.includes("JsonSerializers.") ||
    plan.groups.some((group) =>
      group.operations.some((operation) => operation.responseEncoder.includes("JsonSerializers.")),
    );
  const usesXmlCodecs =
    plan.xmlCodecDeclarations.length > 0 ||
    inputDecoderText.includes("XmlCodecs.") ||
    plan.groups.some((group) =>
      group.operations.some((operation) => operation.responseEncoder.includes("XmlCodecs.")),
    );
  const usesStringifyJson = plan.groups.some((group) =>
    group.operations.some((operation) => operation.responseEncoder.includes("stringifyJson(")),
  );
  const lines: string[] = [];

  // --- Header ---
  lines.push("// AUTO-GENERATED by @typespex/http-emitter — do not edit");
  lines.push("");

  // --- Imports (multi-line) ---
  const runtimeTypes = ["ServerOperation"];
  if (plan.jsonSerializerDeclarations.length > 0) runtimeTypes.push("JsonSerializer");
  if (plan.xmlCodecDeclarations.length > 0) runtimeTypes.push("XmlCodec");
  lines.push(`import type { ${runtimeTypes.join(", ")} } from "@typespex/http-server";`);
  lines.push("import {");
  lines.push("  Either,");
  lines.push("  createHints,");
  lines.push("  emptyHints,");
  lines.push("  ResponseEncoders,");
  if (usesJsonSerializers) lines.push("  JsonSerializers,");
  if (usesXmlCodecs) lines.push("  XmlCodecs,");
  if (usesStringifyJson) lines.push("  stringifyJson,");
  for (const name of plan.inputDecoderImports) {
    lines.push(`  ${name},`);
  }
  lines.push('} from "@typespex/http-server";');
  lines.push(`import * as ServerHints from "./${plan.fileNames.serverHints}.js";`);
  if (plan.operationModelImports.length > 0) {
    lines.push(
      `import type { ${plan.operationModelImports.join(", ")} } from "./${plan.fileNames.models}.js";`,
    );
  }
  lines.push("");
  if (plan.operationPayloadTypeAliases.length > 0) {
    lines.push(...plan.operationPayloadTypeAliases);
    lines.push("");
  }
  if (plan.jsonSerializerDeclarations.length > 0) {
    lines.push(...plan.jsonSerializerDeclarations);
    lines.push("");
  }
  if (plan.xmlCodecDeclarations.length > 0) {
    lines.push(...plan.xmlCodecDeclarations);
    lines.push("");
  }

  // --- Input decoders + Operations per group ---
  const emittedHoisted = new Set<string>();
  for (const group of plan.groups) {
    const inputsName = `${group.exportName}Input`;
    const outputsName = `${group.exportName}Output`;
    const allEntries: InputDecoderEntry[] = [];

    const allHoisted = new Set<string>();
    for (const operation of group.operations) {
      const decoder = operation.inputDecoder;
      allEntries.push(...decoder.inputEntries);
      for (const declaration of decoder.hoistedDecoders) {
        if (!emittedHoisted.has(declaration)) allHoisted.add(declaration);
      }
    }

    // Emit hoisted lazy decoders for recursive models
    for (const line of allHoisted) {
      lines.push(line);
      emittedHoisted.add(line);
    }
    if (allHoisted.size > 0) lines.push("");

    // Emit grouped input decoders object
    if (allEntries.length > 0) {
      lines.push(`const ${inputsName} = {`);
      for (const entry of allEntries) {
        for (const line of entry.lines) {
          lines.push(line);
        }
      }
      lines.push("};");
      lines.push("");
    }

    // Emit grouped output encoders object
    lines.push(`const ${outputsName} = {`);
    for (const operation of group.operations) {
      lines.push(`  ${tsObjectKey(operation.propertyName)}: ${operation.responseEncoder},`);
    }
    lines.push("};");
    lines.push("");

    // Emit operations
    lines.push(`export const ${group.exportName}Operations = {`);

    for (const operation of group.operations) {
      const decoder = operation.inputDecoder;

      lines.push(`  ${tsObjectKey(operation.propertyName)}: {`);
      emitEndpoint(lines, plan.serviceName, operation);

      // Keep the Promise boundary without wrapping helpers that already provide it.
      const asyncPrefix = decoder.isAsync && !decoder.forwardsPromise ? "async " : "";
      if (decoder.needsPathParams) {
        lines.push(`    decodeInput: ${asyncPrefix}(request, pathParams) =>`);
      } else if (decoder.isAsync) {
        lines.push(`    decodeInput: ${asyncPrefix}(request) =>`);
      } else {
        lines.push(`    decodeInput: () =>`);
      }
      lines.push(`      ${decoder.decodeExpression},`);
      if (decoder.decodeNativePathExpression) {
        lines.push(`    decodeNativePathInput: (pathParams) =>`);
        lines.push(`      ${decoder.decodeNativePathExpression},`);
      }

      emitResultEncoderLine(lines, operation, outputsName);

      lines.push(`  } satisfies ServerOperation<${operation.inputType}, ${operation.resultType}>,`);
      lines.push("");
    }

    lines.push("} as const;");
    lines.push("");
  }

  addTemporalImport(lines, "value");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Endpoint emission — compact
// ---------------------------------------------------------------------------

function emitEndpoint(
  lines: string[],
  serviceName: string,
  operation: {
    serviceHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    namespaces: ReadonlyArray<{
      name: string;
      fullName: string;
      hints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
    }>;
    name: string;
    operationId: string;
    method: string;
    path: string;
    routePatterns: readonly RoutePattern[];
    routeSelection?: {
      readonly headers?: readonly {
        readonly name: string;
        readonly values: readonly string[];
        readonly kind: "exact" | "media-type";
      }[];
      readonly query?: readonly {
        readonly name: string;
        readonly value: string;
      }[];
    };
    operationHints: ReadonlyArray<{ keyExportName: string; valueExpression: string }>;
  },
): void {
  lines.push("    endpoint: {");
  lines.push(
    `      service: { name: ${tsLiteral(serviceName)}, hints: ${emitHintsExpression(operation.serviceHints)} },`,
  );

  if (operation.namespaces.length === 0) {
    lines.push("      namespaces: [],");
  } else {
    lines.push("      namespaces: [");
    for (const ns of operation.namespaces) {
      lines.push(
        `        { name: ${tsLiteral(ns.name)}, fullName: ${tsLiteral(ns.fullName)}, hints: ${emitHintsExpression(ns.hints)} },`,
      );
    }
    lines.push("      ],");
  }

  lines.push("      operation: {");
  lines.push(`        name: ${tsLiteral(operation.name)},`);
  lines.push(`        operationId: ${tsLiteral(operation.operationId)},`);
  lines.push(`        method: ${tsLiteral(operation.method)} as const,`);
  lines.push(`        path: ${tsLiteral(operation.path)},`);
  if (operation.routePatterns.length === 1) {
    lines.push(`        routePattern: ${tsLiteral(operation.routePatterns[0])},`);
  } else {
    lines.push(`        routePatterns: ${tsLiteral(operation.routePatterns)},`);
  }
  if (operation.routeSelection) {
    lines.push(`        routeSelection: ${tsLiteral(operation.routeSelection)},`);
  }
  lines.push(`        hints: ${emitHintsExpression(operation.operationHints)},`);
  lines.push("      },");
  lines.push("    },");
}

// ---------------------------------------------------------------------------
// Encode emission — uses structured results, no regex parsing
// ---------------------------------------------------------------------------

function emitResultEncoderLine(
  lines: string[],
  operation: {
    propertyName: string;
    resultType: string;
  },
  outputsName: string,
): void {
  const encoderAccess = tsPropertyAccess(outputsName, operation.propertyName);
  if (operation.resultType === "void") {
    lines.push(`    encodeResult: () => ${encoderAccess}.encode(undefined),`);
  } else {
    lines.push(
      `    encodeResult: (result: ${operation.resultType}) => ${encoderAccess}.encode(result),`,
    );
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitHintsExpression(
  entries: ReadonlyArray<{ keyExportName: string; valueExpression: string }>,
): string {
  if (entries.length === 0) return "emptyHints()";
  const items = entries
    .map((e) => `[${tsPropertyAccess("ServerHints", e.keyExportName)}, ${e.valueExpression}]`)
    .join(", ");
  return `createHints([${items}])`;
}
