import { describe, expect, test } from "bun:test";
import {
  COMPILER_PLAN_VERSION,
  type JsonWirePlan,
  type OperationPlan,
  type ServicePlan,
} from "@typespex/compiler-core/unstable";
import { createServerArtifacts } from "../src/artifacts.js";
import type { PlannedServer, PlannedTool } from "../src/types.js";

describe("MCP planning boundary", () => {
  test("renders repeatably from a cloned data-only plan", () => {
    const input: JsonWirePlan = {
      version: COMPILER_PLAN_VERSION,
      schema: { type: "object" },
      semanticType: '{ Phantom: string; value: Pet; literal: "Phantom" }',
      wireType: '{ Phantom: string; value: Pet; literal: "Phantom" }',
      referencedTypes: ["Pet"],
    };
    const server = createPlanningFixture(input);

    const cloned = structuredClone(server);
    const first = createServerArtifacts(cloned, []);
    const second = createServerArtifacts(cloned, []);
    const operations = first.find((artifact) => artifact.artifact === "Test.mcp-operations");

    expect(second).toEqual(first);
    expect(operations?.content).toContain('import type { Pet } from "./models.js";');
    expect(operations?.content).not.toContain("import type { Pet, Phantom }");
  });

  test("keeps version 1 plans without structural references renderable", () => {
    const server = createPlanningFixture({
      version: COMPILER_PLAN_VERSION,
      schema: { type: "object" },
      semanticType: "Pet",
      wireType: "Pet",
    });

    const operations = createServerArtifacts(server, []).find(
      (artifact) => artifact.artifact === "Test.mcp-operations",
    );

    expect(operations?.content).toContain('import type { Pet, Phantom } from "./models.js";');
  });
});

function createPlanningFixture(input: JsonWirePlan): PlannedServer {
  const operation: OperationPlan = {
    version: COMPILER_PLAN_VERSION,
    name: "inspect",
    input,
  };
  const service: ServicePlan = {
    version: COMPILER_PLAN_VERSION,
    name: "Test",
    namespace: "Test",
    types: [
      {
        version: COMPILER_PLAN_VERSION,
        key: "Pet",
        name: "Pet",
        semanticType: "Pet",
        wireType: "Pet",
      },
      {
        version: COMPILER_PLAN_VERSION,
        key: "Phantom",
        name: "Phantom",
        semanticType: "Phantom",
        wireType: "Phantom",
      },
    ],
    operations: [operation],
  };
  const tool: PlannedTool = {
    plan: operation,
    name: "inspect",
    symbolName: "Inspect",
    allowsVoid: true,
    requiresTaggedResult: false,
  };
  return {
    plan: service,
    modelModule: {
      banner: "// Generated by TypeSpex. Do not edit.",
      imports: [],
      declarations: [
        "export interface Pet { id: string; }",
        "export interface Phantom { id: string; }",
      ],
    },
    symbolName: "Test",
    outputDir: "test",
    fileNames: {
      models: "models",
      operations: "mcp-operations",
      server: "mcp-server",
      httpBridge: "mcp-http-bridge",
      stdio: "mcp-stdio",
      node: "mcp-node",
      bun: "mcp-bun",
      express: "mcp-express",
      hono: "mcp-hono",
    },
    tools: [tool],
    version: "1.0.0",
    modes: { native: true, httpBridge: false },
  };
}
