import { typescriptString, type JsonWirePlan } from "@typespex/compiler-core/unstable";
import { renderSchemaDocument, renderSchemaReference } from "./render-schema-document.js";
import type { PlannedServer, PlannedTool } from "./types.js";

export function renderOperations(server: PlannedServer): string {
  const schemaDocument = renderSchemaDocument(server.schemaDocument);

  const tools = server.tools
    .map((tool) => {
      const fields = [
        `name: ${typescriptString(tool.name)}`,
        ...(tool.title ? [`title: ${typescriptString(tool.title)}`] : []),
        ...(tool.description ? [`description: ${typescriptString(tool.description)}`] : []),
        ...(tool.icons ? [`icons: ${typescriptString(tool.icons)}`] : []),
        ...(tool.annotations ? [`annotations: ${typescriptString(tool.annotations)}`] : []),
        `input: ${schemaReference(tool, "Input", tool.plan.input)}`,
        ...(tool.plan.success
          ? [`success: ${schemaReference(tool, "Success", tool.plan.success)}`]
          : []),
        ...(tool.plan.errors
          ? [`errors: ${schemaReference(tool, "Error", tool.plan.errors)}`]
          : []),
        ...(tool.allowsVoid ? ["voidResult: true"] : []),
        ...(tool.requiresTaggedResult ? ["requiresTaggedResult: true"] : []),
      ];
      return `{ ${fields.join(", ")} }`;
    })
    .join(",\n");

  const modelTypes = collectModelTypesForImport(server);
  const modelImport =
    modelTypes.length > 0
      ? `import type { ${modelTypes.join(", ")} } from "./${server.fileNames.models}.js";`
      : "";
  const aliases = server.tools
    .map((tool) => {
      const input = tool.plan.input;
      const success = tool.plan.success;
      const errors = tool.plan.errors;
      return `${emitSemanticAndWireAliases(tool.symbolName, "Input", input)}
${success ? emitSemanticAndWireAliases(tool.symbolName, "Success", success) : `export type ${tool.symbolName}Success = never;`}
export type ${tool.symbolName}Output = ${
        [
          ...(success ? [`${tool.symbolName}Success`] : []),
          ...(tool.allowsVoid ? ["void"] : []),
        ].join(" | ") || "never"
      };
${errors ? emitSemanticAndWireAliases(tool.symbolName, "Error", errors) : `export type ${tool.symbolName}Error = never;`}`;
    })
    .join("\n\n");

  return `// Generated by @typespex/mcp-emitter. Do not edit.
import { createSchemaDocument, type McpToolDefinition } from "@typespex/mcp-server";
${modelImport}

${aliases}

${schemaDocument}

export const mcpTools = [
${tools}
] as const satisfies readonly McpToolDefinition[];
`;
}

function collectModelTypesForImport(server: PlannedServer): string[] {
  const availableModelTypes = [
    ...new Set(server.plan.types.flatMap((type) => [type.semanticType, type.wireType])),
  ];
  const wirePlans = server.tools.flatMap((tool) =>
    [tool.plan.input, tool.plan.success, tool.plan.errors].filter(
      (plan): plan is JsonWirePlan => plan !== undefined,
    ),
  );

  // Version 1 plans predate structural reference metadata. Importing every
  // planned model is a safe compatibility fallback that avoids parsing
  // rendered TypeScript expressions to reconstruct compiler information.
  if (wirePlans.some((plan) => plan.referencedTypes === undefined)) {
    return availableModelTypes;
  }

  const referencedTypeNames = new Set(wirePlans.flatMap((plan) => plan.referencedTypes ?? []));
  return availableModelTypes.filter((type) => referencedTypeNames.has(type));
}

function schemaReference(
  tool: PlannedTool,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  return renderSchemaReference(
    `${tool.symbolName}${kind}`,
    operationWireAlias(tool.symbolName, kind, plan),
    `${tool.symbolName}${kind}`,
  );
}

function operationWireAlias(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  return plan.wireType === plan.semanticType ? `${symbolName}${kind}` : `${symbolName}${kind}Wire`;
}

function emitSemanticAndWireAliases(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  const semanticName = `${symbolName}${kind}`;
  const wire =
    plan.wireType === plan.semanticType
      ? ""
      : `\nexport type ${symbolName}${kind}Wire = ${plan.wireType};`;
  return `export type ${semanticName} = ${plan.semanticType};${wire}`;
}
