import { camelCase, typescriptString } from "@typespex/compiler-core/unstable";
import type { HttpWireOperationPlan } from "@typespex/http-client";
import type { McpLauncher } from "./lib.js";
import { normalizeIcons } from "./render-metadata.js";
import type { PlannedServer, PlannedTool } from "./types.js";

export function renderServer(server: PlannedServer, launchers: readonly McpLauncher[]): string {
  const implementation = {
    name: server.plan.name,
    version: server.metadata.version,
    ...(server.metadata.icons ? { icons: normalizeIcons(server.metadata.icons) } : {}),
    ...(server.metadata.websiteUrl ? { websiteUrl: String(server.metadata.websiteUrl) } : {}),
  };

  const configuredApplicationType =
    server.modes.native && server.modes.httpBridge
      ? `NativeMcpApplication<${server.symbolName}McpHandlers> | McpHttpBridgeApplication`
      : server.modes.native
        ? `NativeMcpApplication<${server.symbolName}McpHandlers>`
        : "McpHttpBridgeApplication";
  const usesHttpTransport = launchers.some((launcher) => launcher !== "stdio");
  const usesStdioTransport = launchers.includes("stdio");
  const transportFields = [
    ...(usesHttpTransport ? ["readonly http?: McpHttpServerOptions;"] : []),
    ...(usesStdioTransport ? ["readonly stdio?: McpStdioOptions;"] : []),
  ];
  const applicationType =
    transportFields.length > 0
      ? `(${configuredApplicationType}) & { ${transportFields.join(" ")} }`
      : configuredApplicationType;
  const exportedAliases = server.tools.flatMap(operationExportedAliases).join(", ");
  const applicationImports = [
    "type McpHandlersFor",
    ...(server.modes.native ? ["type NativeMcpApplication"] : []),
  ];
  const bridgeImports = server.modes.httpBridge
    ? `import {
  createMcpHttpBridgeApplication,
  type McpHttpBridgeApplication,
} from "@typespex/mcp-http-bridge";
import { mcpHttpBridgeOperations } from "./${server.fileNames.httpBridge}.js";`
    : "";
  const transportImports = [
    ...(usesHttpTransport
      ? ['import type { McpHttpServerOptions } from "@typespex/mcp-transport-http";']
      : []),
    ...(usesStdioTransport
      ? ['import type { McpStdioOptions } from "@typespex/mcp-transport-stdio";']
      : []),
  ].join("\n");
  const serverApplication = server.modes.httpBridge
    ? `const serverApplication =
    application.kind === "http-bridge"
      ? createMcpHttpBridgeApplication(mcpHttpBridgeOperations, application)
      : application;`
    : "const serverApplication = application;";

  return `// Generated by @typespex/mcp-emitter. Do not edit.
import {
  createMcpServer,
  ${applicationImports.join(",\n  ")},
} from "@typespex/mcp-server";
${bridgeImports}
${transportImports}
import { mcpTools } from "./${server.fileNames.operations}.js";
export type { ${exportedAliases} } from "./${server.fileNames.operations}.js";

export type ${server.symbolName}McpHandlers = McpHandlersFor<typeof mcpTools>;

export type ${server.symbolName}McpApplication = ${applicationType};

export function define${server.symbolName}McpApplication<const Application extends ${server.symbolName}McpApplication>(
  application: Application,
): Application {
  return application;
}

export function create${server.symbolName}McpServer(application: ${server.symbolName}McpApplication) {
  ${serverApplication}
  return createMcpServer(
    {
      implementation: ${typescriptString(implementation)},
      ${server.metadata.instructions ? `instructions: ${typescriptString(server.metadata.instructions)},` : ""}
    },
    mcpTools,
    serverApplication,
  );
}
`;
}

function operationExportedAliases(tool: PlannedTool): string[] {
  const aliases = [
    `${tool.symbolName}Input`,
    `${tool.symbolName}Success`,
    `${tool.symbolName}Output`,
    `${tool.symbolName}Error`,
  ];
  if (tool.plan.input.wireType !== tool.plan.input.semanticType) {
    aliases.push(`${tool.symbolName}InputWire`);
  }
  if (tool.plan.success && tool.plan.success.wireType !== tool.plan.success.semanticType) {
    aliases.push(`${tool.symbolName}SuccessWire`);
  }
  if (tool.plan.errors && tool.plan.errors.wireType !== tool.plan.errors.semanticType) {
    aliases.push(`${tool.symbolName}ErrorWire`);
  }
  return aliases;
}

export function renderLauncher(server: PlannedServer, launcher: McpLauncher): string {
  const module = server.applicationModule ?? "./application.js";
  const applicationImports = `import applicationDefinition from ${typescriptString(module)};
import {
  create${server.symbolName}McpServer,
  type ${server.symbolName}McpApplication,
} from "./${server.fileNames.server}.js";`;
  const renderLauncherModule = (
    launcherImports: string,
    body: string,
  ): string => `// Generated by @typespex/mcp-emitter. Do not edit.
${launcherImports}
${applicationImports}

const application: ${server.symbolName}McpApplication = applicationDefinition;

${body}`;
  const factory = `() => create${server.symbolName}McpServer(application)`;
  switch (launcher) {
    case "stdio":
      return renderLauncherModule(
        `import { serveMcpStdio } from "@typespex/mcp-transport-stdio";`,
        `export const ${camelCase(server.symbolName)}McpStdioServer = serveMcpStdio(
  ${factory},
  application.stdio,
);
`,
      );
    case "node":
      return renderLauncherModule(
        `import { createServer } from "node:http";
import { toNodeHandler } from "@typespex/adapter-node";
import {
  createMcpHttpHandler,
  resolveMcpHttpServerOptions,
} from "@typespex/mcp-transport-http";`,
        `const options = resolveMcpHttpServerOptions(application.http);
const mcpHandler = createMcpHttpHandler(${factory}, application.http);
const nodeHandler = toNodeHandler({ handle: mcpHandler.fetch });
let closeMcpHandlerPromise: Promise<void> | undefined;
const closeMcpHandler = () => (closeMcpHandlerPromise ??= mcpHandler.close());
export const ${camelCase(server.symbolName)}McpNodeServer = createServer(
  (request, response) => void nodeHandler(request, response),
);
${camelCase(server.symbolName)}McpNodeServer.on("close", () => void closeMcpHandler());
try {
  await new Promise<void>((resolve, reject) => {
    const onError = (error: Error) => {
      ${camelCase(server.symbolName)}McpNodeServer.off("listening", onListening);
      reject(error);
    };
    const onListening = () => {
      ${camelCase(server.symbolName)}McpNodeServer.off("error", onError);
      resolve();
    };
    ${camelCase(server.symbolName)}McpNodeServer.once("error", onError);
    ${camelCase(server.symbolName)}McpNodeServer.once("listening", onListening);
    ${camelCase(server.symbolName)}McpNodeServer.listen(options.port, options.host);
  });
} catch (error) {
  await closeMcpHandler();
  throw error;
}

export async function close${server.symbolName}McpNodeServer(): Promise<void> {
  if (${camelCase(server.symbolName)}McpNodeServer.listening) {
    await new Promise<void>((resolve, reject) => {
      ${camelCase(server.symbolName)}McpNodeServer.close((error) =>
        error ? reject(error) : resolve(),
      );
    });
  }
  await closeMcpHandler();
}
`,
      );
    case "bun":
      return renderLauncherModule(
        `import { toBunHandler } from "@typespex/adapter-bun";
import {
  createMcpHttpHandler,
  resolveMcpHttpServerOptions,
} from "@typespex/mcp-transport-http";`,
        `const options = resolveMcpHttpServerOptions(application.http);
const mcpHandler = createMcpHttpHandler(${factory}, application.http);
const bunHandler = toBunHandler({ handle: mcpHandler.fetch });
export const ${camelCase(server.symbolName)}McpBunServer = Bun.serve({
  hostname: options.host,
  port: options.port,
  fetch: bunHandler.fetch,
  error(error) {
    options.onError?.(error);
    return new Response("Internal server error.", { status: 500 });
  },
});
let closePromise: Promise<void> | undefined;
export function close${server.symbolName}McpBunServer(): Promise<void> {
  return (closePromise ??= (async () => {
    try {
      await ${camelCase(server.symbolName)}McpBunServer.stop(true);
    } finally {
      await mcpHandler.close();
    }
  })());
}
`,
      );
    case "express":
      return renderLauncherModule(
        `import {
  toExpressHandler,
  type ExpressRequestHandler,
} from "@typespex/adapter-express";
import { createMcpHttpHandler } from "@typespex/mcp-transport-http";`,
        `const mcpHandler = createMcpHttpHandler(${factory}, application.http);
export const ${camelCase(server.symbolName)}McpExpressHandler: ExpressRequestHandler = toExpressHandler({
  handle: mcpHandler.fetch,
});
let closePromise: Promise<void> | undefined;
export const close${server.symbolName}McpExpressHandler = () =>
  (closePromise ??= mcpHandler.close());
`,
      );
    case "hono":
      return renderLauncherModule(
        `import { toHonoApp } from "@typespex/adapter-hono";
import { createMcpHttpHandler } from "@typespex/mcp-transport-http";`,
        `const mcpHandler = createMcpHttpHandler(${factory}, application.http);
export const ${camelCase(server.symbolName)}McpHonoApp = toHonoApp({
  handle: mcpHandler.fetch,
});
let closePromise: Promise<void> | undefined;
export const close${server.symbolName}McpHonoApp = () =>
  (closePromise ??= mcpHandler.close());
`,
      );
  }
}

export function renderHttpBridge(server: PlannedServer): string {
  const operations = Object.fromEntries(
    server.tools.flatMap((tool) =>
      tool.http ? [[tool.name, toHttpBridgeOperation(tool.http)] as const] : [],
    ),
  );
  return `// Generated by @typespex/mcp-emitter. Do not edit.
import type { HttpBridgeOperation } from "@typespex/mcp-http-bridge";

export const mcpHttpBridgeOperations = ${typescriptString(operations)} as const satisfies Readonly<Record<string, HttpBridgeOperation>>;
`;
}

function toHttpBridgeOperation(plan: HttpWireOperationPlan): unknown {
  return {
    version: plan.version,
    id: plan.operationId,
    method: plan.method,
    path: plan.path,
    ...(plan.literalQuery ? { literalQuery: plan.literalQuery } : {}),
    parameters: plan.parameters.map((parameter) => ({
      source: parameter.source,
      name: parameter.wireName,
      location: parameter.location,
      required: parameter.required,
      ...(parameter.style ? { style: parameter.style } : {}),
      ...(parameter.explode !== undefined ? { explode: parameter.explode } : {}),
      ...(parameter.allowReserved !== undefined ? { allowReserved: parameter.allowReserved } : {}),
      ...(parameter.value ? { value: parameter.value } : {}),
    })),
    ...(plan.requestBody
      ? {
          body: {
            ...(plan.requestBody.source ? { source: plan.requestBody.source } : {}),
            ...(plan.requestBody.fields ? { fields: plan.requestBody.fields } : {}),
            kind: plan.requestBody.kind,
            ...(plan.requestBody.contentTypeSource
              ? { contentTypeSource: plan.requestBody.contentTypeSource }
              : {}),
            ...(plan.requestBody.mediaTypes ? { mediaTypes: plan.requestBody.mediaTypes } : {}),
            ...(plan.requestBody.multipartParts
              ? { multipartParts: plan.requestBody.multipartParts }
              : {}),
            ...(plan.requestBody.value ? { value: plan.requestBody.value } : {}),
            ...(!plan.requestBody.contentTypeSource && plan.requestBody.contentTypes[0]
              ? { contentType: plan.requestBody.contentTypes[0] }
              : {}),
          },
        }
      : {}),
    responses: plan.responses.map((response) => ({
      statuses: response.statusCodes,
      ...(response.contentTypes.length > 0 ? { mediaTypes: response.contentTypes } : {}),
      kind: response.kind,
      ...(response.bodyValue ? { bodyValue: response.bodyValue } : {}),
      ...(response.multipartParts ? { multipartParts: response.multipartParts } : {}),
      ...(response.error ? { error: true } : {}),
      ...(response.bodyTarget ? { bodyTarget: response.bodyTarget } : {}),
      ...(response.statusTarget ? { statusTarget: response.statusTarget } : {}),
      ...(response.contentTypeTarget ? { contentTypeTarget: response.contentTypeTarget } : {}),
      ...(response.headers
        ? {
            headers: response.headers.map((header) => ({
              name: header.wireName,
              target: header.target,
              ...(header.collection ? { collection: true } : {}),
              ...(header.value ? { value: header.value } : {}),
            })),
          }
        : {}),
    })),
    ...(plan.servers ? { servers: plan.servers } : {}),
    ...(plan.auth ? { auth: plan.auth } : {}),
  };
}
