import { getDoc, getSummary } from "@typespec/compiler";
import { typescriptString, type JsonWirePlan } from "@typespex/compiler-core/unstable";
import { normalizeIcons } from "./render-metadata.js";
import { renderSchemaDocument, renderSchemaReference } from "./render-schema-document.js";
import type { PlannedServer, PlannedTool } from "./types.js";

export function renderOperations(server: PlannedServer): string {
  const schemaDocument = renderSchemaDocument(server.tools);

  const tools = server.tools
    .map((tool) => {
      const metadata = tool.metadata;
      const description = getDoc(server.planner.program, tool.operation);
      const title = metadata.title ?? getSummary(server.planner.program, tool.operation);
      const fields = [
        `name: ${typescriptString(tool.name)}`,
        ...(title ? [`title: ${typescriptString(title)}`] : []),
        ...(description ? [`description: ${typescriptString(description)}`] : []),
        ...(metadata.icons ? [`icons: ${typescriptString(normalizeIcons(metadata.icons))}`] : []),
        ...(tool.annotations ? [`annotations: ${typescriptString(tool.annotations)}`] : []),
        `input: ${schemaReference(tool, "Input", tool.plan.input)}`,
        ...(tool.plan.success
          ? [`success: ${schemaReference(tool, "Success", tool.plan.success)}`]
          : []),
        ...(tool.plan.errors
          ? [`errors: ${schemaReference(tool, "Error", tool.plan.errors)}`]
          : []),
        ...(tool.allowsVoid ? ["voidResult: true"] : []),
        ...(tool.requiresTaggedResult ? ["requiresTaggedResult: true"] : []),
      ];
      return `{ ${fields.join(", ")} }`;
    })
    .join(",\n");

  const referencedTypeNames = new Set(
    server.tools.flatMap((tool) =>
      [tool.plan.input, tool.plan.success, tool.plan.errors].flatMap((plan) =>
        plan
          ? [plan.semanticType, plan.wireType].flatMap((expression) =>
              referencedTypeIdentifiers(expression),
            )
          : [],
      ),
    ),
  );
  const modelTypes = [
    ...new Set(server.plan.types.flatMap((type) => [type.semanticType, type.wireType])),
  ].filter((type) => referencedTypeNames.has(type));
  const modelImport =
    modelTypes.length > 0
      ? `import type { ${modelTypes.join(", ")} } from "./${server.fileNames.models}.js";`
      : "";
  const aliases = server.tools
    .map((tool) => {
      const input = tool.plan.input;
      const success = tool.plan.success;
      const errors = tool.plan.errors;
      return `${emitSemanticAndWireAliases(tool.symbolName, "Input", input)}
${success ? emitSemanticAndWireAliases(tool.symbolName, "Success", success) : `export type ${tool.symbolName}Success = never;`}
export type ${tool.symbolName}Output = ${
        [
          ...(success ? [`${tool.symbolName}Success`] : []),
          ...(tool.allowsVoid ? ["void"] : []),
        ].join(" | ") || "never"
      };
${errors ? emitSemanticAndWireAliases(tool.symbolName, "Error", errors) : `export type ${tool.symbolName}Error = never;`}`;
    })
    .join("\n\n");

  return `// Generated by @typespex/mcp-emitter. Do not edit.
import { createSchemaDocument, type McpToolDefinition } from "@typespex/mcp-server";
${modelImport}

${aliases}

${schemaDocument}

export const mcpTools = [
${tools}
] as const satisfies readonly McpToolDefinition[];
`;
}

function schemaReference(
  tool: PlannedTool,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  return renderSchemaReference(
    `${tool.symbolName}${kind}`,
    operationWireAlias(tool.symbolName, kind, plan),
    `${tool.symbolName}${kind}`,
  );
}

function operationWireAlias(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  return plan.wireType === plan.semanticType ? `${symbolName}${kind}` : `${symbolName}${kind}Wire`;
}

function emitSemanticAndWireAliases(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  const semanticName = `${symbolName}${kind}`;
  const wire =
    plan.wireType === plan.semanticType
      ? ""
      : `\nexport type ${symbolName}${kind}Wire = ${plan.wireType};`;
  return `export type ${semanticName} = ${plan.semanticType};${wire}`;
}

function referencedTypeIdentifiers(expression: string): string[] {
  const withoutStrings = expression.replace(/"(?:\\.|[^"\\])*"/g, (value) =>
    " ".repeat(value.length),
  );
  return [...withoutStrings.matchAll(/[A-Za-z_$][A-Za-z0-9_$]*/g)].flatMap((match) => {
    const identifier = match[0];
    const offset = match.index + identifier.length;
    return /^\s*\??\s*:/.test(withoutStrings.slice(offset)) ? [] : [identifier];
  });
}
