import { getDoc, getSummary } from "@typespec/compiler";
import {
  camelCase,
  typescriptIdentifier,
  typescriptString,
  type JsonWirePlan,
} from "@typespex/compiler-core/unstable";
import { normalizeIcons } from "./render-metadata.js";
import { isSchemaRecord } from "./schema-utils.js";
import type { PlannedServer, PlannedTool } from "./types.js";

export function renderOperations(server: PlannedServer): string {
  const sharedDefinitions = collectSharedDefinitions(server.tools);
  const definitions = server.tools
    .map((tool) => {
      const input = emitSchemaDefinition(
        `${camelCase(tool.symbolName)}Input`,
        tool.plan.input,
        operationWireAlias(tool.symbolName, "Input", tool.plan.input),
        `${tool.symbolName}Input`,
        sharedDefinitions,
      );
      const success = tool.plan.success
        ? emitSchemaDefinition(
            `${camelCase(tool.symbolName)}Success`,
            tool.plan.success,
            operationWireAlias(tool.symbolName, "Success", tool.plan.success),
            `${tool.symbolName}Success`,
            sharedDefinitions,
          )
        : "";
      const errors = tool.plan.errors
        ? emitSchemaDefinition(
            `${camelCase(tool.symbolName)}Errors`,
            tool.plan.errors,
            operationWireAlias(tool.symbolName, "Error", tool.plan.errors),
            `${tool.symbolName}Error`,
            sharedDefinitions,
          )
        : "";
      return [input, success, errors].filter(Boolean).join("\n");
    })
    .join("\n");

  const tools = server.tools
    .map((tool) => {
      const metadata = tool.metadata;
      const description = getDoc(server.planner.program, tool.operation);
      const title = metadata.title ?? getSummary(server.planner.program, tool.operation);
      return `{
        name: ${typescriptString(tool.name)},
        ${title ? `title: ${typescriptString(title)},` : ""}
        ${description ? `description: ${typescriptString(description)},` : ""}
        ${metadata.icons ? `icons: ${typescriptString(normalizeIcons(metadata.icons))},` : ""}
        ${tool.annotations ? `annotations: ${typescriptString(tool.annotations)},` : ""}
        input: ${camelCase(tool.symbolName)}Input,
        ${tool.plan.success ? `success: ${camelCase(tool.symbolName)}Success,` : ""}
        ${tool.plan.errors ? `errors: ${camelCase(tool.symbolName)}Errors,` : ""}
        ${tool.allowsVoid ? "voidResult: true," : ""}
        ${tool.requiresTaggedResult ? "requiresTaggedResult: true," : ""}
      }`;
    })
    .join(",\n");

  const referencedTypeNames = new Set(
    server.tools.flatMap((tool) =>
      [tool.plan.input, tool.plan.success, tool.plan.errors].flatMap((plan) =>
        plan
          ? [plan.semanticType, plan.wireType].flatMap((expression) =>
              referencedTypeIdentifiers(expression),
            )
          : [],
      ),
    ),
  );
  const modelTypes = [
    ...new Set(server.plan.types.flatMap((type) => [type.semanticType, type.wireType])),
  ].filter((type) => referencedTypeNames.has(type));
  const modelImport =
    modelTypes.length > 0
      ? `import type { ${modelTypes.join(", ")} } from "./${server.fileNames.models}.js";`
      : "";
  const aliases = server.tools
    .map((tool) => {
      const input = tool.plan.input;
      const success = tool.plan.success;
      const errors = tool.plan.errors;
      return `${emitSemanticAndWireAliases(tool.symbolName, "Input", input)}
${success ? emitSemanticAndWireAliases(tool.symbolName, "Success", success) : `export type ${tool.symbolName}Success = never;`}
export type ${tool.symbolName}Output = ${
        [
          ...(success ? [`${tool.symbolName}Success`] : []),
          ...(tool.allowsVoid ? ["void"] : []),
        ].join(" | ") || "never"
      };
${errors ? emitSemanticAndWireAliases(tool.symbolName, "Error", errors) : `export type ${tool.symbolName}Error = never;`}`;
    })
    .join("\n\n");

  return `// Generated by @typespex/mcp-emitter. Do not edit.
import { createSchema, type McpToolDefinition } from "@typespex/mcp-server";
${modelImport}

${aliases}

${sharedDefinitions.declarations.join("\n")}

${definitions}

export const mcpTools = [
${tools}
] as const satisfies readonly McpToolDefinition[];
`;
}

function operationWireAlias(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  return plan.wireType === plan.semanticType ? `${symbolName}${kind}` : `${symbolName}${kind}Wire`;
}

function emitSemanticAndWireAliases(
  symbolName: string,
  kind: "Input" | "Success" | "Error",
  plan: JsonWirePlan,
): string {
  const semanticName = `${symbolName}${kind}`;
  const wire =
    plan.wireType === plan.semanticType
      ? ""
      : `\nexport type ${symbolName}${kind}Wire = ${plan.wireType};`;
  return `export type ${semanticName} = ${plan.semanticType};${wire}`;
}

function referencedTypeIdentifiers(expression: string): string[] {
  const withoutStrings = expression.replace(/"(?:\\.|[^"\\])*"/g, (value) =>
    " ".repeat(value.length),
  );
  return [...withoutStrings.matchAll(/[A-Za-z_$][A-Za-z0-9_$]*/g)].flatMap((match) => {
    const identifier = match[0];
    const offset = match.index + identifier.length;
    return /^\s*\??\s*:/.test(withoutStrings.slice(offset)) ? [] : [identifier];
  });
}

function emitSchemaDefinition(
  name: string,
  plan: JsonWirePlan,
  wireType: string,
  semanticType: string,
  shared: SharedDefinitions,
): string {
  const typeArguments =
    wireType === semanticType ? `<${semanticType}>` : `<${wireType}, ${semanticType}>`;
  return `const ${name} = createSchema${typeArguments}({
    schema: ${emitSharedDocument(plan.schema, "$defs", shared.schema)},
    ${plan.codec ? `codec: ${emitSharedDocument(plan.codec, "definitions", shared.codec)},` : ""}
  });`;
}

interface SharedDefinitions {
  readonly schema: ReadonlyMap<string, string>;
  readonly codec: ReadonlyMap<string, string>;
  readonly declarations: readonly string[];
}

function collectSharedDefinitions(tools: readonly PlannedTool[]): SharedDefinitions {
  const schema = new Map<string, string>();
  const codec = new Map<string, string>();
  const declarations: string[] = [];
  const usedNames = new Set<string>();
  const plans = tools.flatMap((tool) =>
    [tool.plan.input, tool.plan.success, tool.plan.errors].filter(
      (plan): plan is JsonWirePlan => plan !== undefined,
    ),
  );
  const collect = (
    document: unknown,
    property: "$defs" | "definitions",
    target: Map<string, string>,
    suffix: string,
  ): void => {
    if (!isSchemaRecord(document) || !isSchemaRecord(document[property])) return;
    for (const [definitionName, definition] of Object.entries(document[property])) {
      const key = JSON.stringify(definition);
      if (target.has(key)) continue;
      const base = typescriptIdentifier(
        camelCase(`${definitionName}${suffix}Definition`),
        `${suffix}Definition`,
      );
      let identifier = base;
      let index = 2;
      while (usedNames.has(identifier)) identifier = `${base}${index++}`;
      usedNames.add(identifier);
      target.set(key, identifier);
      declarations.push(`const ${identifier} = ${typescriptString(definition)} as const;`);
    }
  };
  for (const plan of plans) {
    collect(plan.schema, "$defs", schema, "Schema");
    if (plan.codec) collect(plan.codec, "definitions", codec, "Codec");
  }
  return { schema, codec, declarations };
}

function emitSharedDocument(
  document: unknown,
  property: "$defs" | "definitions",
  identifiers: ReadonlyMap<string, string>,
): string {
  if (!isSchemaRecord(document) || !isSchemaRecord(document[property])) {
    return typescriptString(document);
  }
  const members = Object.entries(document)
    .filter(([name]) => name !== property)
    .map(([name, value]) => `${typescriptString(name)}: ${typescriptString(value)}`);
  const definitions = Object.entries(document[property])
    .map(([name, definition]) => {
      const identifier = identifiers.get(JSON.stringify(definition));
      return `${typescriptString(name)}: ${identifier ?? typescriptString(definition)}`;
    })
    .join(", ");
  members.push(`${typescriptString(property)}: { ${definitions} }`);
  return `{ ${members.join(", ")} }`;
}
